<definition>
	<command name="assertTextEquals">
		<case locator-key1="DOCUMENT_EXTRACTED_METADATA_FIELD">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>