<definition>
	<command name="assertClick">
		<case locator-key1="COMPLETED_TABLE_ASSET_TITLE">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="COMPLETED_TABLE_ASSET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>