<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="ASSIGNED_TO_ME_MENULIST_">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>

		<case locator-key1="ASSIGNED_TO_ME_TABLE_ACTIONS">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>

		<case locator-key1="DIALOG_BOX_OK_BUTTON">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case comparator="contains" locator1="//div[@id='workflowMyRolesTasksPanelContent']//tr[3]/td">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="ASSIGNED_TO_ME_TABLE_ASSET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ASSIGNED_TO_MY_ROLES_TABLE_ASSET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="DIALOG_BOX_COMMENT_FIELD">
			<execute function="Type#clickAtType" />
		</case>

		<case locator-key1="DIALOG_BOX_DUE_DATE">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="DIALOG_BOX_DUE_DATE_TIME">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>