<definition>
	<command name="click">
		<default>
			<execute function="Click#clickSikuli" />
		</default>
	</command>

	<command name="type">
		<default>
			<execute function="Type#typeSikuli" />
		</default>
	</command>
</definition>