<definition>
	<command name="assertTextEquals">
		<case locator-key1="AVAILABLE_LANGUAGES_AVAILABLE_SELECT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="AVAILABLE_LANGUAGES_CURRENT_SELECT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="AVAILABLE_LANGUAGES_CURRENT_PRESENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>