<definition>
	<command name="assertClick">
		<case locator-key1="PUBLIC_PAGES_OPEN_PAGES">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="close">
		<case locator1="home - Liferay">
			<execute function="Close#closeWindow" />
		</case>
	</command>
</definition>