<definition>
	<command name="assertElementNotPresent">
		<case locator-key1="SOURCE_SCOPE_FIELD_FILTER_AND_VALUE">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="SOURCE_SCOPE_FILTER_BY_FIELD_CHECKBOX">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SOURCE_SCOPE_FIELD_FILTER_AND_VALUE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SOURCE_SCOPE_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>