<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator1="//ul[@class='nav control-panel-bar-secondary nav-pills']//a[contains">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>