<definition>
	<command name="type">
		<case locator-key1="DESCRIPTION_FIELD">
			<execute function="Type#type" />
		</case>

		<case locator-key1="NAME_FIELD">
			<execute function="Type#type" />
		</case>
	</command>
</definition>