<definition>
	<command name="assertTextEquals">
		<case locator-key1="END_DATE_FIELD">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="START_DATE_FIELD">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>