<definition>
	<command name="assertTextEquals">
		<case locator-key1="PROFILE_INFO_ADDRESS_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_EMAIL_ADDRESS_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_INSTANT_MESSENGER_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_INTRODUCTION_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_PHONE_NUMBERS_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_PROJECTS_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_SMS_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_SOCIAL_NETWORK_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_TAGS_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PROFILE_INFO_WEBSITES_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="EDIT_PROFILE_PICTURE_BUTTON">
			<execute function="Click#makeVisibleClickAt" />
		</case>
	</command>
</definition>