<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SUCCESS_MESSAGE_RESTORE_LOCATION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="CONFIRMATION">
			<execute function="Confirm#waitForConfirmation" />
		</case>
	</command>
</definition>