<definition>
	<command name="assertClick">
		<case locator-key1="ADD_MENULIST_ORGANIZATION_ROLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ADD_MENULIST_REGULAR_ROLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ADD_MENULIST_SITE_ROLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ROLE_MENULIST_ASSIGN_MEMBERS">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ROLE_MENULIST_DEFINE_PERMISSIONS">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ROLE_MENULIST_DELETE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ROLE_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="isElementPresent">
		<case comparator="startsWith" locator-key1="ROLE_TABLE_ACTIONS_">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>
</definition>