<definition>
	<command name="assertClick">
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="UPDATE_ASSOCIATIONS_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="STATUS_AVAILABLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>