<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="ADD_MENULIST_">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="ROLE_MENULIST_">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="isElementPresent">
		<case comparator="startsWith" locator-key1="ROLE_TABLE_ACTIONS_">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>
</definition>