<definition>
	<command name="assertTextEquals">
		<case locator-key1="NOTIFICATION_MENU_NOTIFICATION_ENTRY_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="NOTIFICATION_MENU_REQUEST_ENTRY_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="assertTextNotEquals">
		<case locator-key1="GO_TO_SITE_LIST">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="DASHBOARD">
			<execute function="Click#textClickAtAndWait" value1="Dashboard" />
		</case>

		<case locator-key1="GO_TO">
			<execute function="Click#pauseClickAt" />
		</case>

		<case locator-key1="GO_TO_ADD_SITE_BUTTON">
			<execute function="Click#pauseClickAt" />
		</case>

		<case locator-key1="GO_TO_SITES_DIRECTORY_BUTTON">
			<execute function="Click#pauseClickAt" />
		</case>

		<case locator-key1="NOTIFICATION_MENU_VIEW_NOTIFICATIONS_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="NOTIFICATION_MENU_VIEW_REQUESTS_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="Click#makeVisibleClickAt" />
		</case>
	</command>
</definition>