<definition>
	<command name="assertTextNotEquals">
		<case locator-key1="SITE_LIST">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="DELETE_SITE_ICON">
			<execute function="Click#pauseTextClickAt" />
		</case>
	</command>

	<command name="clickNoError">
		<case locator-key1="DELETE_SITE_ICON">
			<execute function="ClickNoError#pauseClick" />
		</case>
	</command>
</definition>