<definition>
	<command name="assertTextEquals">
		<case locator-key1="BREADCRUMB_1">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="BREADCRUMB_2">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="BREADCRUMB_3">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="BREADCRUMB_4">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>