<definition>
	<command name="assertClick">
		<case locator-key1="MODIFIED_RANGE_FACET_TIME_RANGE">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="ASSET_TYPE_FACET_ASSET">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="USER_FACET_USER_NAME">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="ASSET_ENTRY_TABLE_TYPE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>