<definition>
	<command name="click">
		<case locator-key1="LOCATOR_KEY">
			<execute function="Function#function" />
		</case>
		<case comparator="contains" locator-key1="OCATOR_KE">
			<execute function="Function#function" />
		</case>
		<case comparator="endsWith" locator-key1="_KEY">
			<execute function="Function#function" />
		</case>
		<case comparator="startsWith" locator-key1="LOCATOR_">
			<execute function="Function#function" />
		</case>
		<default>
			<execute function="Function#function" />
		</default>
	</command>
</definition>