<definition>
	<command name="name">
		<default>
			<description message="" />
			<execute function="Function#function" />
			<execute function="Function#function" />
		</default>
	</command>
</definition>