<definition>
	<command name="assertClick">
		<case locator-key1="NAVIGATION_APPLICATIONS">
			<execute function="AssertClick#assertTextClickAtAddApplication" />
		</case>

		<case locator-key1="NAVIGATION_CONTENT">
			<execute function="AssertClick#assertTextClickAtAddApplication" />
		</case>

		<case locator-key1="NAVIGATION_PAGE">
			<execute function="AssertClick#assertTextClickAtAddApplication" />
		</case>
	</command>
</definition>