<definition>
	<command name="assertTextEquals">
		<case locator-key1="CONFIGURATION_SAVE_LOCATION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="CONFIGURATION_SAVE_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>