<definition>
	<command name="click">
		<case locator-key="ADD_ENTRY">
			<execute function="Click#valueClickAtAndWait" value="Add Blogs Entry" />
		</case>
		<case locator-key="DELETE_ENTRY">
			<execute function="Click#valueClickAtAndWait" value="Delete" />
		</case>
	</command>
</definition>