<definition>
	<command name="assertClick">
		<case locator-key1="PUBLISH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWaitCKEditor" />
		</case>
		<case locator-key1="SUBMIT_FOR_PUBLICATION_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWaitCKEditor" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>
	</command>
</definition>