<definition>
	<command name="click">
		<case locator-key1="RECYCLE_BIN_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ENTRY_TABLE_ALL_CHECKBOX">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>
</definition>