<definition>
	<command name="assertTextEquals">
		<case locator-key1="CONTENT_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="CATEGORIES_CATEGORY_UNSELECTED">
			<execute function="Click#click" />
		</case>
	</command>

	<command name="isElementNotPresent">
		<case locator-key1="CATEGORIZATION_TAGS_ADD_BUTTON">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>
	</command>
</definition>