<definition>
	<command name="assertClick">
		<case locator-key1="NEW_MESSAGE_BUTTON">
			<execute function="AssertClick#assertTextClickAt" />
		</case>

		<case locator-key1="DELETE_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="MARK_AS_UNREAD_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>