<definition>
	<command name="assertClick">
		<case locator-key1="NEW_MESSAGE_BUTTON">
			<execute function="AssertClick#assertTextClickAt" />
		</case>

		<case locator-key1="DELETE_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="MARK_AS_UNREAD_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="MARK_AS_UNREAD_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="MARK_AS_READ_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="DELETE_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>