<definition>
	<command name="assertClick">
		<case locator-key1="NEW_MESSAGE_BUTTON">
			<execute function="AssertClick#assertValueClickAt" value1="New Message" />
		</case>

		<case locator-key1="DELETE_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>

		<case locator-key1="MARK_AS_UNREAD_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
	</command>
</definition>