<definition>
	<command name="assertClick">
		<case locator-key1="ORGANIZATION_INFORMATION_ORGANIZATION_SITE">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="DETAILS_TYPE">
			<execute function="AssertTextEquals#assertValue" />
		</case>
	</command>
</definition>