<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ORGANIZATION_INFORMATION_ORGANIZATION_SITE">
			<execute function="Click#partialTextClickAt" value1="Organization Site" />
		</case>
		<case locator-key1="SAVE_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Save" />
		</case>
	</command>
</definition>