<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>
</definition>