<definition>
	<command name="assertTextEquals">
		<case locator-key1="INFO_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="No users were found." />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Search" />
		</case>
		<case locator-key1="DEACTIVATE">
			<execute function="Click#textClickAtAndWait" value1="Deactivate" />
		</case>
		<case locator-key1="DELETE">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
		<case comparator="startsWith" locator-key1="USER_TABLE_FIRST_NAME_">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>
</definition>