<definition>
	<command name="assertClick">
		<case locator-key1="AVAILABLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="BACK">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="CURRENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="UPDATE_ASSOCIATIONS_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="USER_TABLE_ALL_CHECKBOX">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>
</definition>