<definition>
	<command name="click">
		<case locator-key1="I_AGREE_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="I Agree" />
		</case>
		<case locator-key1="I_DISAGREE_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="I Disagree" />
		</case>
	</command>
</definition>