<definition>
	<command name="assertClick">
		<case locator-key1="TITLE_DROPDOWN_SELECTION">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="TITLE_DROPDOWN">
			<execute function="Click#pauseClickAt" />
		</case>
	</command>
</definition>