<definition>
	<command name="assertClick">
		<case locator-key1="ADD_MENULIST_ADT_TEMPLATE">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>

		<case locator-key1="ADD">
			<execute function="AssertClick#assertTextClick" />
		</case>

		<case locator-key1="DELETE_BUTTON">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ADT_TABLE_ALL_CHECKBOX">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>
</definition>