<definition>
	<command name="click">
		<case locator-key1="CATEGORIES_RECYCLE_BIN_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
		<case locator-key1="THREADS_RECYCLE_BIN_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="THREAD_TABLE_ALL_CHECKBOX">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>
</definition>