<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case comparator="startsWith" locator-key1="MESSAGE_EDIT_">
			<execute function="Click#textClickAtAndWait" value1="Edit" />
		</case>
		<case comparator="startsWith" locator-key1="MESSAGE_REPLY_">
			<execute function="Click#textClickAtAndWait" value1="Reply" />
		</case>
	</command>
</definition>