<definition>
	<command name="assertTextEquals">
		<case locator-key1="NEW_PROCESS_FIELDS_SELECT_FIELD">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="NEW_PROCESS_FIELDS_HTML_FIELD_EDITOR">
			<execute function="Type#typeFrame" />
		</case>
	</command>
</definition>