<definition>
	<command name="assertTextEquals">
		<case locator-key1="OTHERWISE_PANEL_SELECTED_CONTENT_TYPE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="RULE_PANEL_SELECTED_DISPLAY_CONTENT_TYPE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>