<definition>
	<command name="assertClick">
		<case locator-key1="PUBLISH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWaitCKEditor" />
		</case>

		<case locator-key1="CATEGORIZATION_TAGS_SELECT_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SAVE_STATUS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>
	</command>
</definition>