<definition>
	<command name="click">
		<case comparator="startsWith" locator-key1="ENTRY_TITLE_">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="PUBLISH">
			<execute function="Click#valueClickAtAndWait" value1="Publish" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT">
			<execute function="Type#typeFrame" />
		</case>
	</command>
</definition>