<definition>
	<command name="click">
		<case locator-key1="COMMENTS_ADD">
			<execute function="Click#textClickAt" value1="Be the first." />
		</case>
		<case locator-key1="COMMENTS_REPLY_BUTTON">
			<execute function="Click#textClickAt" value1="Reply" />
		</case>
	</command>
</definition>