<definition>
	<command name="assertClick">
		<case locator-key1="PERMISSIONS_MORE_OPTIONS_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="PERMISSIONS_HIDE_OPTIONS_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SAVE_STATUS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="copy">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Copy#ckEditorCopy" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ABSTRACT_DROPDOWN_COLLAPSED">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>

	<command name="paste">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Paste#ckEditorPaste" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="DISPLAY_DATE_DATE_INPUT">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="DISPLAY_DATE_TIME_INPUT">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="CATEGORIZATION_TAGS_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>