<definition>
	<command name="assertTextEquals">
		<case locator-key1="PORTLET_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" value1="Welcome to Liferay Portal" />
		</case>
		<case locator-key1="PORTLET_TITLE">
			<execute function="AssertTextEquals#assertText" value1="Hello World" />
		</case>
	</command>
</definition>