<definition>
	<command name="assertTextEquals">
		<case locator-key1="PORTLET_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PORTLET_TITLE">
			<execute function="AssertTextEquals#assertText" />
		</case>
	</command>
</definition>