<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="ACTIONS_MENULIST_">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="ADD_MENULIST_">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="TOOLBAR_">
			<execute function="AssertClick#waitForDMHomeAssertTextEqualsClick" />
		</case>
	</command>
</definition>