<definition>
	<command name="assertTextEquals">
		<case locator-key1="ALL_FILES_READY_TO_BE_SAVED_SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>