<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="TOOLBAR_">
			<execute function="AssertClick#assertTextClick" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case comparator="startsWith" locator-key1="MARKETING_">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case comparator="startsWith" locator-key1="METADATA_">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ERROR_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="DOCUMENT_INFO_TAGS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="METADATA_PANEL_NUMBER">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>