<definition>
	<command name="click">
		<case locator-key1="MEMBERS_LIST_NAME">
			<execute function="Click#pauseTextClickAt" />
		</case>
	</command>

	<command name="close">
		<case locator-key1="MEMBERS_POP_UP_WINDOW">
			<execute function="Close#closeWindow" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="MEMBERS_LIST_SEARCH">
			<execute function="Type#typePause" />
		</case>
	</command>
</definition>