<definition>
	<command name="assertClick">
		<case locator-key1="UPDATE_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="EDITOR_FIELD">
			<execute function="Type#typeWaitForNotValueNull" />
		</case>
	</command>
</definition>