<definition>
	<command name="assertTextEquals">
		<case locator-key1="STRUCTURE">
			<execute function="AssertTextEquals#assertValue" />
		</case>
	</command>

	<command name="isElementNotPresent">
		<case locator-key1="DESCRIPTION_FIELD">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="NAME_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="SCRIPT_CONTENT_FIELD">
			<execute function="Type#typeAceEditor" />
		</case>
	</command>
</definition>