<definition>
	<command name="assertTextNotEquals">
		<case locator-key1="EVENTS_DISPLAY_TODAYS_EVENTS">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>

		<case locator-key1="EVENTS_DISPLAY_UPCOMING_EVENTS">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>
	</command>
</definition>