<definition>
	<command name="assertTextEquals">
		<case locator-key1="PUBLISHER_PORTLET_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" value1="${randomNumber}" />
		</case>
	</command>
</definition>