<definition>
	<command name="assertTextEquals">
		<case locator-key1="ORGANIZATION_TABLE_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ORGANIZATION_TABLE_TOOLTIP">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="USER_TABLE_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>