<definition>
	<command name="assertClick">
		<case locator-key1="RECENT_BLOGS_ENTRY_READ_MORE_LINK">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="RECENT_BLOGS_ENTRY_AUTHOR">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>