<definition>
	<command name="assertTextEquals">
		<case locator-key1="PORTLET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="CONFIRMATION">
			<execute function="Confirm#waitForConfirmation" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="NAVIGATION_PAGE">
			<execute function="IsElementPresent#isElementPresentClickNavigation" />
		</case>
	</command>

	<command name="mouseOver">
		<case locator-key1="NAVIGATION_PAGE">
			<execute function="MouseOver#mouseOverClickNavigation" />
		</case>
	</command>
</definition>