<definition>
	<command name="assertClick">
		<case locator-key1="ASSIGNED_TO_ME_TABLE_ASSET_TITLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="ASSIGNED_TO_MY_ROLES_TABLE_ASSET_TITLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="ASSIGNED_TO_ME_TABLE_ASSET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ASSIGNED_TO_MY_ROLES_TABLE_ASSET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case comparator="contains" locator1="//div[@id='workflowMyRolesTasksPanelContent']//tr[3]/td">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>
</definition>