<definition>
	<command name="assertClick">
		<case locator-key1="ADD_NEW_MENULIST_BASIC_WEB_CONTENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="ASSET_ABSTRACT_READ_MORE">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>

		<case locator-key1="ASSET_ABSTRACT_VIEW">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>

		<case locator-key1="DISPLAY_ICON_EDIT">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertElementPresent">
		<case locator-key1="ASSET_ABSTRACT_BOOKMARK_LIFERAY_LOGO">
			<execute function="AssertElementPresent#assertElementPresent" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="ASSET_ABSTRACT_DESCRIPTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ASSET_ABSTRACT_DETAIL_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="METADATA_CATEGORY">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="METADATA_VOCABULARY">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="assertTextNotEquals">
		<case locator-key1="ASSET_ABSTRACT_TITLE">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>
	</command>
</definition>