<definition>
	<command name="assertClick">
		<case locator-key1="ADD_NEW_MENULIST_WEB_CONTENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ASSET_READ_MORE">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>
	</command>
</definition>