<definition>
	<command name="assertClick">
		<case locator-key1="MENU_CONTENT">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="PUBLISH_BUTTON">
			<execute function="AssertClick#assertTextClickAtCKEditor" ignore-javascript-error="b is null" />
		</case>

		<case locator-key1="SAVE_AS_DRAFT_BUTTON">
			<execute function="AssertClick#assertTextClickAtCKEditor" ignore-javascript-error="b is null" />
		</case>

		<case locator-key1="SUBMIT_FOR_PUBLICATION_BUTTON">
			<execute function="AssertClick#assertTextClickAtCKEditor" ignore-javascript-error="b is null" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>

		<case locator-key1="TITLE_FIELD">
			<execute function="Type#typeWaitForCKEditor" />
		</case>
	</command>
</definition>