<definition>
	<command name="assertClick">
		<case locator-key1="SOURCE_SCOPE_MENULIST_OTHER_SITE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="SOURCE_SCOPE_ASSET_TYPE_SELECT">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="SOURCE_SCOPE_FIELD_FILTER_AND_VALUE">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="SOURCE_SCOPE_FILTER_BY_FIELD_CHECKBOX">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SOURCE_SCOPE_FIELD_FILTER_AND_VALUE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>