<definition>
	<command name="assertClick">
		<case locator-key1="SITES_TABLE_CHOOSE_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertElementPresent">
		<case locator-key1="SITES_TABLE_CHOOSE_BUTTON">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
	</command>
</definition>