<definition>
	<command name="assertTextEquals">
		<case comparator="startsWith" locator-key1="DOCUMENT_CONVERSION_">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ASSET_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>