<definition>
	<command name="assertClick">
		<case locator-key1="ADD_MENULIST_ADT_TEMPLATE">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>

		<case locator-key1="ADD">
			<execute function="AssertClick#assertTextClick" />
		</case>
	</command>
</definition>