<definition>
	<command name="assertTextEquals">
		<case locator-key1="MESSAGE_BODY_ATTACHMENT_1">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case comparator="startsWith" locator-key1="MESSAGE_BODY_">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>