<definition>
	<command name="assertElementPresent">
		<case locator-key1="THREAD_MENULIST_MOVE_TO_THE_RECYCLE_BIN">
			<execute function="AssertElementPresent#assertVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="CATEGORY_TABLE_ACTIONS">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="INFO_MESSAGE_THREAD">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="SUCCESS_MESSAGE_RECYCLE_BIN">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="THREAD_TABLE_ACTIONS">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="THREAD_TABLE_LAST_POST">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="THREAD_TABLE_ALL_CHECKBOX">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>
</definition>