<definition>
	<command name="assertClick">
		<case locator-key1="NOTIFICATIONS_CONTENT">
			<execute function="Click#partialTextClickAtAndWait" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="NOTIFICATIONS_VIEW_ALL_NOTIFICATIONS">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>
</definition>