<definition>
	<command name="addSelection">
		<default>
			<execute function="AddSelection#addSelection" />
		</default>
	</command>

	<command name="antCommand">
		<default>
			<execute function="AntCommand#antCommand" />
		</default>
	</command>

	<command name="assertAlertNotPresent">
		<default>
			<description message="Fail if the alert is present." />

			<execute function="AssertAlertNotPresent#assertAlertNotPresent" />
		</default>
	</command>

	<command name="assertChecked">
		<default>
			<execute function="AssertChecked#assertChecked" />
		</default>
	</command>

	<command name="assertClick">
		<case comparator="contains" locator1="/input">
			<execute function="AssertClick#assertValueClickAt" />
		</case>

		<default>
			<description message="Click on the ${locator1} with the value ${value1}." />

			<execute function="AssertClick#assertTextClickAt" />
		</default>
	</command>

	<command name="assertClickNoError">
		<case comparator="contains" locator1="/input">
			<execute function="AssertClickNoError#assertValueClick" />
		</case>

		<default>
			<description message="Click on the ${locator1} with the value ${value1}." />

			<execute function="AssertClickNoError#assertTextClick" />
		</default>
	</command>

	<command name="assertConsoleTextNotPresent">
		<default>
			<description message="Assert that the text ${value1} is NOT present within the console output." />

			<execute function="AssertConsoleTextNotPresent#assertConsoleTextNotPresent" />
		</default>
	</command>

	<command name="assertConsoleTextPresent">
		<default>
			<description message="Assert that the text ${value1} is present within the console output." />

			<execute function="AssertConsoleTextPresent#assertConsoleTextPresent" />
		</default>
	</command>

	<command name="assertElementNotPresent">
		<default>
			<description message="Assert that the ${locator1} is NOT present." />

			<execute function="AssertElementNotPresent#assertElementNotPresent" />
		</default>
	</command>

	<command name="assertElementPresent">
		<default>
			<description message="Assert that the ${locator1} is present." />

			<execute function="AssertElementPresent#assertVisible" />
		</default>
	</command>

	<command name="assertHTMLSourceTextNotPresent">
		<default>
			<execute function="AssertHTMLSourceTextNotPresent#assertHTMLSourceTextNotPresent" />
		</default>
	</command>

	<command name="assertHTMLSourceTextPresent">
		<default>
			<execute function="AssertHTMLSourceTextPresent#assertHTMLSourceTextPresent" />
		</default>
	</command>

	<command name="assertLocation">
		<default>
			<execute function="AssertLocation#assertLocation" />
		</default>
	</command>

	<command name="assertNotChecked">
		<default>
			<execute function="AssertNotChecked#assertNotChecked" />
		</default>
	</command>

	<command name="assertNotVisible">
		<default>
			<description message="Assert that the ${locator1} is NOT visible." />

			<execute function="AssertNotVisible#assertNotVisible" />
		</default>
	</command>

	<command name="assertSelectedLabel">
		<default>
			<execute function="AssertSelectedLabel#assertSelectedLabel" />
		</default>
	</command>

	<command name="assertTextEquals">
		<case comparator="contains" locator1="/input">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<default>
			<description message="Assert that the text at the ${locator1} is ${value1}." />

			<execute function="AssertTextEquals#assertText" />
		</default>
	</command>

	<command name="assertTextNotEquals">
		<case comparator="contains" locator1="/input">
			<execute function="AssertTextNotEquals#assertNotValue" />
		</case>

		<default>
			<description message="Assert that the text at the ${locator1} is NOT ${value1}." />

			<execute function="AssertTextNotEquals#assertNotText" />
		</default>
	</command>

	<command name="assertTextNotPresent">
		<default>
			<description message="Assert that the text ${value1} is NOT present." />

			<execute function="AssertTextNotPresent#assertTextNotPresent" />
		</default>
	</command>

	<command name="assertTextPresent">
		<default>
			<description message="Assert that the text ${value1} is present." />

			<execute function="AssertTextPresent#assertTextPresent" />
		</default>
	</command>

	<command name="assertValue">
		<default>
			<execute function="AssertValue#assertValue" />
		</default>
	</command>

	<command name="assertVisible">
		<default>
			<description message="Assert that the ${locator1} is visible." />

			<execute function="AssertVisible#assertVisible" />
		</default>
	</command>

	<command name="check">
		<default>
			<execute function="Check#clickAt" />
		</default>
	</command>

	<command name="click">
		<default>
			<description message="Click on the ${locator1}." />

			<execute function="Click#clickAt" />
		</default>
	</command>

	<command name="clickNoError">
		<default>
			<description message="Click on the ${locator1}." />

			<execute function="ClickNoError#click" />
		</default>
	</command>

	<command name="close">
		<default>
			<execute function="Close#close" />
		</default>
	</command>

	<command name="confirm">
		<default>
			<description message="Assert confirmation window has the value ${value1}." />

			<execute function="Confirm#assertConfirmation" />
		</default>
	</command>

	<command name="copy">
		<case comparator="contains" locator1="/input">
			<execute function="Copy#valueCopy" />
		</case>

		<default>
			<execute function="Copy#textCopy" />
		</default>
	</command>

	<command name="doubleClick">
		<default>
			<execute function="DoubleClick#doubleClickAt" />
		</default>
	</command>

	<command name="downloadTempFile">
		<default>
			<execute function="DownloadTempFile#downloadTempFile" />
		</default>
	</command>

	<command name="dragAndDrop">
		<default>
			<execute function="DragAndDrop#dragAndDropToObject" />
		</default>
	</command>

	<command name="isElementNotPresent">
		<default>
			<execute function="IsElementNotPresent#isElementNotPresent" />
		</default>
	</command>

	<command name="isElementPresent">
		<default>
			<execute function="IsElementPresent#isElementPresent" />
		</default>
	</command>

	<command name="isHTMLSourceTextPresent">
		<default>
			<execute function="IsHTMLSourceTextPresent#isHTMLSourceTextPresent" />
		</default>
	</command>

	<command name="isNotVisible">
		<default>
			<execute function="IsNotVisible#isNotVisible" />
		</default>
	</command>

	<command name="isTextEqual">
		<case comparator="contains" locator1="/input">
			<execute function="IsTextEqual#isValue" />
		</case>

		<default>
			<execute function="IsTextEqual#isText" />
		</default>
	</command>

	<command name="isTextNotEqual">
		<case comparator="contains" locator1="/input">
			<execute function="IsTextNotEqual#isNotValue" />
		</case>

		<default>
			<execute function="IsTextNotEqual#isNotText" />
		</default>
	</command>

	<command name="isVisible">
		<default>
			<execute function="IsVisible#isVisible" />
		</default>
	</command>

	<command name="keyPress">
		<default>
			<execute function="KeyPress#keyPress" />
		</default>
	</command>

	<command name="makeVisible">
		<default>
			<execute function="MakeVisible#makeVisible" />
		</default>
	</command>

	<command name="mouseDown">
		<default>
			<execute function="MouseDown#mouseDown" />
		</default>
	</command>

	<command name="mouseMove">
		<default>
			<execute function="MouseMove#mouseMove" />
		</default>
	</command>

	<command name="mouseOver">
		<default>
			<description message="Mouse over the ${locator1}." />

			<execute function="MouseOver#mouseOver" />
		</default>
	</command>

	<command name="mouseUp">
		<default>
			<execute function="MouseUp#mouseUp" />
		</default>
	</command>

	<command name="open">
		<default>
			<description message="Open the browser to the URL ${locator1}." />

			<execute function="Open#open" />
		</default>
	</command>

	<command name="paste">
		<default>
			<execute function="Paste#paste" />
		</default>
	</command>

	<command name="pause">
		<default>
			<execute function="Pause#pause" />
		</default>
	</command>

	<command name="refresh">
		<default>
			<execute function="Refresh#refresh" />
		</default>
	</command>

	<command name="scrollWebElementIntoView">
		<default>
			<execute function="ScrollWebElementIntoView#scrollWebElementIntoView" />
		</default>
	</command>

	<command name="select">
		<default>
			<execute function="Select#select" />
		</default>
	</command>

	<command name="selectFrame">
		<case comparator="contains" locator1="/iframe">
			<execute function="SelectFrame#selectFrame" />
		</case>

		<default>
			<execute function="SelectFrame#selectFrameTop" />
		</default>
	</command>

	<command name="selectFrameTop">
		<default>
			<execute function="SelectFrameTop#selectFrameTop" />
		</default>
	</command>

	<command name="selectNoError">
		<default>
			<execute function="SelectNoError#select" />
		</default>
	</command>

	<command name="selectWindow">
		<default>
			<execute function="SelectWindow#selectWindow" />
		</default>
	</command>

	<command name="setWindowSize">
		<default>
			<execute function="SetWindowSize#setWindowSize" />
		</default>
	</command>

	<command name="sikuliAssertElementNotPresent">
		<default>
			<execute function="SikuliAssertElementNotPresent#sikuliAssertElementNotPresent" />
		</default>
	</command>

	<command name="sikuliAssertElementPresent">
		<default>
			<execute function="SikuliAssertElementPresent#sikuliAssertElementPresent" />
		</default>
	</command>

	<command name="sikuliClick">
		<default>
			<description message="Click on the ${locator1}." />

			<execute function="SikuliClick#sikuliClick" />
		</default>
	</command>

	<command name="sikuliDragAndDrop">
		<default>
			<execute function="SikuliDragAndDrop#sikuliDragAndDrop" />
		</default>
	</command>

	<command name="sikuliLeftMouseDown">
		<default>
			<description message="Push left mouse button down." />

			<execute function="SikuliLeftMouseDown#sikuliLeftMouseDown" />
		</default>
	</command>

	<command name="sikuliLeftMouseUp">
		<default>
			<description message="Lift left mouse button up." />

			<execute function="SikuliLeftMouseUp#sikuliLeftMouseUp" />
		</default>
	</command>

	<command name="sikuliMouseMove">
		<default>
			<description message="Mouse over the ${locator1}." />

			<execute function="SikuliMouseMove#sikuliMouseMove" />
		</default>
	</command>

	<command name="sikuliRightMouseDown">
		<default>
			<description message="Push right mouse button down." />

			<execute function="SikuliRightMouseDown#sikuliRightMouseDown" />
		</default>
	</command>

	<command name="sikuliRightMouseUp">
		<default>
			<description message="Lift right mouse button up." />

			<execute function="SikuliRightMouseUp#sikuliRightMouseUp" />
		</default>
	</command>

	<command name="sikuliType">
		<default>
			<description message="Uses Sikuli to type into the ${locator1} with the value ${value1}." />

			<execute function="SikuliType#sikuliType" />
		</default>
	</command>

	<command name="sikuliUploadCommonFile">
		<default>
			<execute function="SikuliUploadCommonFile#sikuliUploadCommonFile" />
		</default>
	</command>

	<command name="sikuliUploadTCatFile">
		<default>
			<execute function="SikuliUploadTCatFile#sikuliUploadTCatFile" />
		</default>
	</command>

	<command name="sikuliUploadTempFile">
		<default>
			<execute function="SikuliUploadTempFile#sikuliUploadTempFile" />
		</default>
	</command>

	<command name="type">
		<default>
			<description message="Type into the ${locator1} with the value ${value1}." />

			<execute function="Type#type" />
		</default>
	</command>

	<command name="typeScreen">
		<default>
			<description message="Type the value ${value1}." />

			<execute function="TypeScreen#typeScreen" />
		</default>
	</command>

	<command name="uncheck">
		<default>
			<execute function="Uncheck#clickAt" />
		</default>
	</command>

	<command name="uploadCommonFile">
		<default>
			<execute function="UploadCommonFile#uploadCommonFile" />
		</default>
	</command>

	<command name="uploadFile">
		<default>
			<execute function="UploadFile#uploadFile" />
		</default>
	</command>

	<command name="uploadTempFile">
		<default>
			<execute function="UploadTempFile#uploadTempFile" />
		</default>
	</command>
</definition>