<definition>
	<command name="assertClick">
		<case locator-key1="OPTIONS_ICON">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>

		<case locator-key1="OPTIONS_MENULIST_CONFIGURATION">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="PORTLET_BODY">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PORTLET_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>