<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="CONTROL_PANEL_">
			<execute function="AssertClick#assertPartialTextClickAtCPNavigation" />
		</case>

		<case comparator="startsWith" locator-key1="SITE_ADMINISTRATION_">
			<execute function="AssertClick#assertPartialTextClickAtCPNavigation" />
		</case>

		<case comparator="startsWith" locator1="link" >
			<execute function="AssertClick#assertTextClickAtNavigation" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="PAGE_DELETE">
			<execute function="AssertElementNotPresent#assertElementNotPresentClickDockbar" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SITE_ADMINISTRATION_NAVIGATION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PORTAL_LOCALIZATION_MESSAGE_INFO">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="NODE_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="click">
		<case comparator="contains" locator1="Link to URL" >
			<execute function="Click#clickAtNonLiferayNavigation" />
		</case>

		<case comparator="startsWith" locator1="link" >
			<execute function="Click#clickAtNavigation" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="PAGE_CONFIRM">
			<execute function="Confirm#waitForConfirmation" />
		</case>
	</command>

	<command name="isElementPresent">
		<case comparator="startsWith" locator-key1="CONTROL_PANEL_">
			<execute function="IsElementPresent#isElementPresentCPNavigation" />
		</case>

		<case comparator="startsWith" locator-key1="PAGE_">
			<execute function="IsElementPresent#isElementPresentClickNavigation" />
		</case>

		<case comparator="startsWith" locator-key1="PORTLET">
			<execute function="IsElementPresent#isElementPresentAfterWait" />
		</case>
	</command>

	<command name="mouseOver">
		<case comparator="startsWith" locator-key1="PAGE_">
			<execute function="MouseOver#mouseOverClickNavigation" />
		</case>

		<case locator-key1="PAGE">
			<execute function="MouseOver#mouseOverClickNavigation" />
		</case>
	</command>
</definition>