<definition>
	<command name="assertElementNotPresent">
		<case locator-key1="ANNOUNCEMENTS_NAVIGATION_NEXT">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="ANNOUNCEMENTS_NAVIGATION_PREVIOUS">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="ANNOUNCEMENTS_ENTRY_ACTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ANNOUNCEMENTS_ENTRY_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ANNOUNCEMENTS_PORTLET_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="CONFIRMATION">
			<execute function="Confirm#waitForConfirmation" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ANNOUNCEMENTS_ENTRY_DELETE_LINK">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>
</definition>