<definition>
	<command name="click">
		<case locator-key1="ADD_PAGE">
			<execute function="Click#textClickAt" value1="Page" />
		</case>
		<case locator-key1="ADD_CONTENT_AND_APPLICATIONS">
			<execute function="Click#partialTextClickAt" value1="Content and Applications" />
		</case>
		<case locator-key1="GO_TO_CONTROL_PANEL">
			<execute function="Click#textClickAtAndWait" value1="Control Panel" />
		</case>
		<case locator-key1="USER_SIGN_OUT">
			<execute function="Click#textClickAtAndWait" value1="Sign Out" />
		</case>
		<case locator-key1="ADD_APPLICATION_LINK">
			<execute function="Click#clickAtApplicationSearch" />
		</case>
	</command>

	<command name="mouseOver">
		<case locator-key1="ADD">
			<execute function="MouseOver#textMouseOverClickDockbar" value1="Add" />
		</case>
		<case locator-key1="MANAGE">
			<execute function="MouseOver#textMouseOverClickDockbar" value1="Manage" />
		</case>
		<case locator-key1="GO_TO">
			<execute function="MouseOver#textMouseOverClickDockbar" value1="Go to" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="ADD_APPLICATION_SEARCH_FIELD">
			<execute function="Type#sendKeysApplicationSearch" />
		</case>
	</command>
</definition>