<definition>
	<command name="assertClick">
		<case locator-key1="ADD">
			<execute function="AssertClick#assertTextClickAtClickSidebar" />
		</case>

		<case locator-key1="ADD_APPLICATION_LINK">
			<execute function="AssertClick#assertTextClickAtAddApplication" />
		</case>

		<case locator-key1="ADD_CONTENT_LINK">
			<execute function="AssertClick#assertTextClickAtAddApplication" />
		</case>

		<case locator-key1="ADD_PAGE_LINK">
			<execute function="AssertClick#assertTextClickAtAddApplication" />
		</case>

		<case locator-key1="ADMIN">
			<execute function="AssertClick#assertTextClickAtClickDockbar" />
		</case>

		<case locator-key1="USER_MY_DASHBOARD">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="USER_MY_ACCOUNT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="USER_NAME">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case comparator="startsWith" locator-key1="ADMIN_SITE_ADMINISTRATION">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case comparator="contains" locator1="//span[@data-title=">
			<execute function="AssertClick#pauseMakeVisibleAssertTextEqualsClickAt" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD">
			<execute function="Click#clickAtSidebarClickAt" />
		</case>

		<case locator-key1="ADMIN">
			<execute function="Click#textClickAtClickDockbar" value1="Admin" />
		</case>

		<case locator-key1="EDIT">
			<execute function="Click#clickAtSidebarClickAt" />
		</case>

		<case locator-key1="MY_SITES">
			<execute function="Click#textClickAtClickDockbar" value1="My Sites" />
		</case>

		<case locator-key1="USER_SIGN_OUT">
			<execute function="Click#clickAtAndWait" />
		</case>

		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="Click#pauseMakeVisibleClickAt" />
		</case>
	</command>

	<command name="isElementNotPresent">
		<case comparator="startsWith" locator1="//div[@id='_145_">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="ADD_APPLICATION_SEARCH_FIELD">
			<execute function="Type#sendKeysApplicationSearch" />
		</case>
	</command>
</definition>