<definition>
	<command name="assertClick">
		<case locator-key1="ADMIN">
			<execute function="AssertClick#assertTextClickAtClickDockbar" />
		</case>

		<case comparator="contains" locator1="//span[@data-title=">
			<execute function="AssertClick#pauseMakeVisibleAssertTextEqualsClickAt" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertElementPresent">
		<case comparator="contains" locator1="//div[@id='_145_embeddedPortletsContent']">
			<execute function="AssertElementPresent#pauseAssertVisible" />
		</case>
	</command>

	<command name="assertNotVisible">
		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="AssertVisible#pauseAssertVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="PAGE_INFO_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="assertVisible">
		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="AssertVisible#pauseAssertVisible" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD">
			<execute function="Click#clickAtSidebarClickAtWaitForScript" />
		</case>

		<case locator-key1="ADMIN">
			<execute function="Click#textClickAtClickDockbar" />
		</case>

		<case locator-key1="EDIT">
			<execute function="Click#clickAtSidebarClickAt" />
		</case>

		<case locator-key1="MY_SITES">
			<execute function="Click#textClickAtClickDockbar" />
		</case>

		<case locator-key1="PREVIEW">
			<execute function="Click#clickAtSidebarClickAt" />
		</case>

		<case comparator="startsWith" locator1="//span[@data-title='">
			<execute function="Click#pauseMakeVisibleClickAt" />
		</case>
	</command>

	<command name="isElementNotPresent">
		<case comparator="startsWith" locator1="//div[@id='_145_">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>
</definition>