<definition>
	<command name="assertClick">
		<case locator-key1="SITE_TABLE_CHILD_SITE">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>

		<case locator-key1="SITE_TABLE_NAME">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="SITE_TABLE_NAME_UNVIEWABLE">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="SITE_MENULIST_SITE_ADMINISTRATION">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>
</definition>