<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE_RECYCLE_BIN">
			<execute function="AssertTextEquals#assertPartialText" value1="The selected item was moved to the Recycle Bin. Undo" />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
		<case comparator="startsWith" locator-key1="THREAD_TABLE_LAST_POST_">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD_CATEGORY_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Add Category" />
		</case>
		<case locator-key1="CATEGORY_MENULIST_RECYCLE_BIN">
			<execute function="Click#textClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
		<case comparator="startsWith" locator-key1="CATEGORY_TABLE_ACTIONS_">
			<execute function="Click#pauseTextClickAt" value1="Actions" />
		</case>
		<case comparator="startsWith" locator-key1="CATEGORY_TABLE_CATEGORY_">
			<execute function="Click#textClickAtAndWait" />
		</case>
		<case locator-key1="POST_NEW_THREAD_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Post New Thread" />
		</case>
		<case locator-key1="THREAD_MENULIST_RECYCLE_BIN">
			<execute function="Click#textClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
		<case comparator="startsWith" locator-key1="THREAD_TABLE_ACTIONS_">
			<execute function="Click#pauseTextClickAt" value1="Actions" />
		</case>
		<case comparator="startsWith" locator-key1="THREAD_TABLE_THREAD_">
			<execute function="Click#textClickAtAndWait" />
		</case>
	</command>
</definition>