<definition>
	<command name="click">
		<case locator-key="PUBLISH">
			<execute function="Click#valueClickAtAndWait" value1="Publish" />
		</case>
	</command>

	<command name="type">
		<case locator-key="BODY">
			<execute function="Type#typeFrame" />
		</case>
	</command>
</definition>