<definition>
	<command name="click">
		<case locator-key1="BLOCK_QUOTE_FIELD">
			<execute function="Click#clickAt" />
		</case>
	</command>

	<command name="copy">
		<case locator-key1="BODY_FIELD">
			<execute function="Copy#ckEditorCopy" />
		</case>
	</command>

	<command name="paste">
		<case locator-key1="BODY_FIELD">
			<execute function="Paste#ckEditorPaste" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="BODY_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>

		<case locator-key1="BODY_FIELD_SOURCE_ON_SEND_KEYS">
			<execute function="Type#sendKeys" />
		</case>
	</command>
</definition>