<definition>
	<command name="assertClick">
		<case locator-key1="PUBLISH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWaitCKEditor" />
		</case>
	</command>

	<command name="select">
		<case locator-key1="FORMAT_DROPDOWN">
			<execute function="Select#pauseSelect" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="BODY_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>

		<case locator-key1="CK_EDITOR_SOURCE_FIELD">
			<execute function="Type#type" />
		</case>
	</command>
</definition>