<definition>
	<command name="click">
		<case locator-key1="PUBLISH_BUTTON">
			<execute function="Click#valueClickAtAndWaitCKEditor" value1="Publish" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="BODY_FIELD">
			<execute function="Type#typeFrame" />
		</case>
	</command>
</definition>