<definition>
	<command name="assertClick">
		<case locator-key1="ADD_CHILD_PAGE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="ADD_FRONTPAGE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="NAVIGATION_ALL_PAGES">
			<execute function="AssertClick#assertTextClickAtAndWait"/>
		</case>
	</command>
</definition>