<definition>
	<command name="click">
		<case locator-key1="ADD_CHILD_PAGE">
			<execute function="Click#textClickAtAndWait" value1="Add Child Page" />
		</case>
		<case locator-key1="ADD_FRONTPAGE">
			<execute function="Click#textClickAtAndWait" value1="This page is empty. Edit it to add some text." />
		</case>
		<case locator-key1="NAVIGATION_ALL_PAGES">
			<execute function="Click#textClickAtAndWait" value1="All Pages" />
		</case>
	</command>
</definition>