<definition>
	<command name="assertElementNotPresent">
		<case locator-key1="ENTRY_CONTENT">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="ENTRY_SCOPE">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>
</definition>