<definition>
	<command name="assertElementPresent">
		<case locator-key1="TASK_PROGRESS_BAR_PERCENT_COMPLETION">
			<execute function="AssertElementPresent#assertElementPresent" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="TASK_PROGRESS_BAR_PERCENT_CLICK">
			<execute function="Click#makeVisibleClickAt" />
		</case>
	</command>
</definition>