<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ASSIGNED_TO_ME_TABLE_ACTIONS">
			<execute function="Click#textClickAt" value1="Actions" />
		</case>
		<case locator-key1="ASSIGNED_TO_ME_MENULIST_APPROVE">
			<execute function="Click#textClickAtAndWait" value1="Approve" />
		</case>
		<case locator-key1="ASSIGNED_TO_ME_MENULIST_REJECT">
			<execute function="Click#textClickAtAndWait" value1="Reject" />
		</case>
		<case locator-key1="ASSIGNED_TO_ME_MENULIST_UPDATE_DUE_DATE">
			<execute function="Click#textClickAtAndWait" value1="Update Due Date" />
		</case>
		<case locator-key1="ASSIGNED_TO_MY_ROLES_TABLE_ACTIONS">
			<execute function="Click#textClickAt" value1="Actions" />
		</case>
		<case locator-key1="ASSIGNED_TO_MY_ROLES_MENULIST_ASSIGN_TO_ME">
			<execute function="Click#textClickAtAndWait" value1="Assign to Me" />
		</case>
		<case locator-key1="ASSIGNED_TO_MY_ROLES_MENULIST_UPDATE_DUE_DATE">
			<execute function="Click#textClickAtAndWait" value1="Update Due Date" />
		</case>
		<case locator-key1="PANEL_CANCEL_BUTTON">
			<execute function="Click#textClickAt" value1="Cancel" />
		</case>
		<case locator-key1="PANEL_OK_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="OK" />
		</case>
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Search" />
		</case>
		<case locator-key1="NAVIGATION_COMPLETED">
			<execute function="Click#textClickAtAndWait" value1="Completed" />
		</case>
		<case locator-key1="NAVIGATION_PENDING">
			<execute function="Click#textClickAtAndWait" value1="Pending" />
		</case>
	</command>
</definition>