<definition>
	<command name="assertTextEquals">
		<case locator-key1="COMMENTS_SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request processed successfully." />
		</case>
		<case locator-key1="DUE_DATE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
		<case locator-key1="PREVIEW_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
		<case locator-key1="STATE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ACTIVITIES">
			<execute function="Click#textClickAt" value1="Activities" />
		</case>
		<case locator-key1="COMMENTS">
			<execute function="Click#textClickAt" value1="Comments" />
		</case>
		<case locator-key1="COMMENTS_ADD_COMMENT">
			<execute function="Click#textClickAt" value1="Add Comment" />
		</case>
		<case locator-key1="COMMENTS_BE_THE_FIRST">
			<execute function="Click#textClickAt" value1="Be the first." />
		</case>
		<case locator-key1="COMMENTS_REPLY_BUTTON">
			<execute function="Click#valueClickAt" value1="Reply" />
		</case>
		<case locator-key1="MENU_WITHDRAW_SUBMISSION">
			<execute function="Click#textClickAtAndWait" value1="Withdraw Submission" />
		</case>
		<case locator-key1="PANEL_OK_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="OK" />
		</case>
		<case locator-key1="PANEL_CANCEL_BUTTON">
			<execute function="Click#textClickAt" value1="Cancel" />
		</case>
		<case locator-key1="PREVIEW">
			<execute function="Click#partialTextClickAt" value1="Preview" />
		</case>
		<case locator-key1="TASKS">
			<execute function="Click#textClickAt" value1="Tasks" />
		</case>
		<case locator-key1="TASKS_TABLE_ACTIONS">
			<execute function="Click#textClickAt" value1="Actions" />
		</case>
		<case locator-key1="TASKS_MENULIST_APPROVE">
			<execute function="Click#textClickAt" value1="Approve" />
		</case>
		<case locator-key1="TASKS_MENULIST_REJECT">
			<execute function="Click#textClickAt" value1="Reject" />
		</case>
	</command>
</definition>