<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="NAVIGATION_DEFINITIONS">
			<execute function="Click#textClickAtAndWait" value1="Definitions" />
		</case>
		<case locator-key1="NAVIGATION_DEFAULT_CONFIGURATIONS">
			<execute function="Click#textClickAtAndWait" value1="Default Configuration" />
		</case>
		<case locator-key1="NAVIGATION_SUBMISSIONS">
			<execute function="Click#textClickAtAndWait" value1="Submissions" />
		</case>
		<case locator-key1="SAVE_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Save" />
		</case>
	</command>
</definition>