<definition>
	<command name="click">
		<case locator-key1="NAVIGATION_COMPLETED">
			<execute function="Click#textClickAtAndWait" value1="Completed" />
		</case>
		<case locator-key1="NAVIGATION_DEFINITIONS">
			<execute function="Click#textClickAtAndWait" value1="Definitions" />
		</case>
		<case locator-key1="NAVIGATION_DEFAULT_CONFIGURATIONS">
			<execute function="Click#textClickAtAndWait" value1="Default Configuration" />
		</case>
		<case locator-key1="NAVIGATION_PENDING">
			<execute function="Click#textClickAtAndWait" value1="Pending" />
		</case>
		<case locator-key1="NAVIGATION_SUBMISSIONS">
			<execute function="Click#textClickAtAndWait" value1="Submissions" />
		</case>
	</command>
</definition>