<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="TOOLBAR_">
			<execute function="AssertClick#waitForDMHomeAssertTextEqualsClick" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="FOLDER_MENULIST_DELETE">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="ERROR_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="DOCUMENT_MENULIST_DOWNLOAD">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="ENTRY_ICON_DOCUMENT_THUMBNAIL">
			<execute function="IsElementPresent#isVisible" />
		</case>

		<case locator-key1="ENTRY_ICON_DOCUMENT_THUMBNAIL_GENERIC">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>
</definition>