<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="TOOLBAR_">
			<execute function="AssertClick#waitForDMHomeAssertTextEqualsClick" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="BREADCRUMB_FOLDER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>