<definition>
	<command name="assertTextEquals">
		<case locator-key1="DISTRIBUTION_SCOPE_SELECT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="assertTextNotEquals">
		<case locator-key1="DISTRIBUTION_SCOPE_SELECT">
			<execute function="AssertTextNotEquals#assertNotPartialText" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrame" />
		</case>

		<case locator-key1="CONTENT_FIELD_FORMATTED_TEXT">
			<execute function="Type#sendKeys" />
		</case>
	</command>
</definition>