<definition>
	<command name="click">
		<case locator-key1="NAVIGATION_CONTACTS_CENTER">
			<execute function="Click#textClickAtAndWait" value1="Contacts Center" />
		</case>

		<case locator-key1="NAVIGATION_MESSAGES">
			<execute function="Click#textClickAtAndWait" value1="Messages" />
		</case>

		<case locator-key1="NAVIGATION_MICROBLOGS">
			<execute function="Click#textClickAtAndWait" value1="Microblogs" />
		</case>

		<case locator-key1="NAVIGATION_TASKS">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>