<definition>
	<command name="assertClick">
		<case locator-key1="DATA_LIST_RECORD_FIELDS_TEXT">
			<execute function="AssertClick#assertTextClick" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="SCRIPT_CONTENT_FIELD">
			<execute function="Type#typeAceEditor" />
		</case>
	</command>
</definition>