<definition>
	<command name="assertClick">
		<case locator-key1="FIRST_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="LAST_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="PRIVATE_MESSAGE_ATTACHMENT_LINK">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PRIVATE_MESSAGE_REPLY_ATTACHMENT_LINK">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PRIVATE_MESSAGE_BODY">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PRIVATE_MESSAGE_REPLY_BODY">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PRIVATE_MESSAGE_USERS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>