<definition>
	<command name="assertClick">
		<case locator-key1="SAVE_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="USER_TABLE_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>