<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
		<case locator-key1="INFO_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="No teams were found." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD_TEAM_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Add Team" />
		</case>
	</command>
</definition>