<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="VIEW_TEAMS">
			<execute function="Click#textClickAtAndWait" value1="View Teams" />
		</case>
	</command>
</definition>