<definition>
	<command name="click">
		<case comparator="startsWith" locator-key1="ROLE_TABLE_TITLE_1">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="ROLES_SEARCH_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Search" />
		</case>
	</command>
</definition>