<definition>
	<command name="assertClick">
		<case locator-key1="ROLES_SEARCH_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="ROLE_TABLE_TITLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>