/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.ac.profile.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.LocalizedModel;
import com.liferay.portal.model.StagedAuditedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the ServiceACProfile service. Represents a row in the &quot;ServiceACProfile&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.ac.profile.model.impl.ServiceACProfileModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.ac.profile.model.impl.ServiceACProfileImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServiceACProfile
 * @see com.liferay.portal.ac.profile.model.impl.ServiceACProfileImpl
 * @see com.liferay.portal.ac.profile.model.impl.ServiceACProfileModelImpl
 * @generated
 */
@ProviderType
public interface ServiceACProfileModel extends BaseModel<ServiceACProfile>,
	LocalizedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a service a c profile model instance should use the {@link ServiceACProfile} interface instead.
	 */

	/**
	 * Returns the primary key of this service a c profile.
	 *
	 * @return the primary key of this service a c profile
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this service a c profile.
	 *
	 * @param primaryKey the primary key of this service a c profile
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this service a c profile.
	 *
	 * @return the uuid of this service a c profile
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this service a c profile.
	 *
	 * @param uuid the uuid of this service a c profile
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the service a c profile ID of this service a c profile.
	 *
	 * @return the service a c profile ID of this service a c profile
	 */
	public long getServiceACProfileId();

	/**
	 * Sets the service a c profile ID of this service a c profile.
	 *
	 * @param serviceACProfileId the service a c profile ID of this service a c profile
	 */
	public void setServiceACProfileId(long serviceACProfileId);

	/**
	 * Returns the company ID of this service a c profile.
	 *
	 * @return the company ID of this service a c profile
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this service a c profile.
	 *
	 * @param companyId the company ID of this service a c profile
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this service a c profile.
	 *
	 * @return the user ID of this service a c profile
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this service a c profile.
	 *
	 * @param userId the user ID of this service a c profile
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this service a c profile.
	 *
	 * @return the user uuid of this service a c profile
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this service a c profile.
	 *
	 * @param userUuid the user uuid of this service a c profile
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this service a c profile.
	 *
	 * @return the user name of this service a c profile
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this service a c profile.
	 *
	 * @param userName the user name of this service a c profile
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this service a c profile.
	 *
	 * @return the create date of this service a c profile
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this service a c profile.
	 *
	 * @param createDate the create date of this service a c profile
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this service a c profile.
	 *
	 * @return the modified date of this service a c profile
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this service a c profile.
	 *
	 * @param modifiedDate the modified date of this service a c profile
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the allowed services of this service a c profile.
	 *
	 * @return the allowed services of this service a c profile
	 */
	@AutoEscape
	public String getAllowedServices();

	/**
	 * Sets the allowed services of this service a c profile.
	 *
	 * @param allowedServices the allowed services of this service a c profile
	 */
	public void setAllowedServices(String allowedServices);

	/**
	 * Returns the name of this service a c profile.
	 *
	 * @return the name of this service a c profile
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this service a c profile.
	 *
	 * @param name the name of this service a c profile
	 */
	public void setName(String name);

	/**
	 * Returns the title of this service a c profile.
	 *
	 * @return the title of this service a c profile
	 */
	public String getTitle();

	/**
	 * Returns the localized title of this service a c profile in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized title of this service a c profile
	 */
	@AutoEscape
	public String getTitle(Locale locale);

	/**
	 * Returns the localized title of this service a c profile in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this service a c profile. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getTitle(Locale locale, boolean useDefault);

	/**
	 * Returns the localized title of this service a c profile in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized title of this service a c profile
	 */
	@AutoEscape
	public String getTitle(String languageId);

	/**
	 * Returns the localized title of this service a c profile in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized title of this service a c profile
	 */
	@AutoEscape
	public String getTitle(String languageId, boolean useDefault);

	@AutoEscape
	public String getTitleCurrentLanguageId();

	@AutoEscape
	public String getTitleCurrentValue();

	/**
	 * Returns a map of the locales and localized titles of this service a c profile.
	 *
	 * @return the locales and localized titles of this service a c profile
	 */
	public Map<Locale, String> getTitleMap();

	/**
	 * Sets the title of this service a c profile.
	 *
	 * @param title the title of this service a c profile
	 */
	public void setTitle(String title);

	/**
	 * Sets the localized title of this service a c profile in the language.
	 *
	 * @param title the localized title of this service a c profile
	 * @param locale the locale of the language
	 */
	public void setTitle(String title, Locale locale);

	/**
	 * Sets the localized title of this service a c profile in the language, and sets the default locale.
	 *
	 * @param title the localized title of this service a c profile
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setTitle(String title, Locale locale, Locale defaultLocale);

	public void setTitleCurrentLanguageId(String languageId);

	/**
	 * Sets the localized titles of this service a c profile from the map of locales and localized titles.
	 *
	 * @param titleMap the locales and localized titles of this service a c profile
	 */
	public void setTitleMap(Map<Locale, String> titleMap);

	/**
	 * Sets the localized titles of this service a c profile from the map of locales and localized titles, and sets the default locale.
	 *
	 * @param titleMap the locales and localized titles of this service a c profile
	 * @param defaultLocale the default locale
	 */
	public void setTitleMap(Map<Locale, String> titleMap, Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(
		com.liferay.portal.ac.profile.model.ServiceACProfile serviceACProfile);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.liferay.portal.ac.profile.model.ServiceACProfile> toCacheModel();

	@Override
	public com.liferay.portal.ac.profile.model.ServiceACProfile toEscapedModel();

	@Override
	public com.liferay.portal.ac.profile.model.ServiceACProfile toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}