<definition>
	<command name="assertTextEquals">
		<case locator-key1="RESOURCES_ACTIONS_TABLE_DESCRIPTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>