/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.adaptive.media.image.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.adaptive.media.image.model.AdaptiveMediaImage;
import com.liferay.adaptive.media.image.model.AdaptiveMediaImageModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the AdaptiveMediaImage service. Represents a row in the &quot;AdaptiveMediaImage&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AdaptiveMediaImageModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AdaptiveMediaImageImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AdaptiveMediaImageImpl
 * @see AdaptiveMediaImage
 * @see AdaptiveMediaImageModel
 * @generated
 */
@ProviderType
public class AdaptiveMediaImageModelImpl extends BaseModelImpl<AdaptiveMediaImage>
	implements AdaptiveMediaImageModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a adaptive media image model instance should use the {@link AdaptiveMediaImage} interface instead.
	 */
	public static final String TABLE_NAME = "AdaptiveMediaImage";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "adaptiveMediaImageId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "configurationUuid", Types.VARCHAR },
			{ "fileVersionId", Types.BIGINT },
			{ "mimeType", Types.VARCHAR },
			{ "height", Types.INTEGER },
			{ "width", Types.INTEGER },
			{ "size_", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("adaptiveMediaImageId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("configurationUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fileVersionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("mimeType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("height", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("width", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("size_", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table AdaptiveMediaImage (uuid_ VARCHAR(75) null,adaptiveMediaImageId LONG not null primary key,groupId LONG,companyId LONG,createDate DATE null,configurationUuid VARCHAR(75) null,fileVersionId LONG,mimeType VARCHAR(75) null,height INTEGER,width INTEGER,size_ LONG)";
	public static final String TABLE_SQL_DROP = "drop table AdaptiveMediaImage";
	public static final String ORDER_BY_JPQL = " ORDER BY adaptiveMediaImage.adaptiveMediaImageId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY AdaptiveMediaImage.adaptiveMediaImageId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.adaptive.media.image.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.adaptive.media.image.model.AdaptiveMediaImage"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.adaptive.media.image.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.adaptive.media.image.model.AdaptiveMediaImage"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.adaptive.media.image.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.adaptive.media.image.model.AdaptiveMediaImage"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long CONFIGURATIONUUID_COLUMN_BITMASK = 2L;
	public static final long FILEVERSIONID_COLUMN_BITMASK = 4L;
	public static final long GROUPID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long ADAPTIVEMEDIAIMAGEID_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.adaptive.media.image.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.adaptive.media.image.model.AdaptiveMediaImage"));

	public AdaptiveMediaImageModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _adaptiveMediaImageId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAdaptiveMediaImageId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _adaptiveMediaImageId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AdaptiveMediaImage.class;
	}

	@Override
	public String getModelClassName() {
		return AdaptiveMediaImage.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("adaptiveMediaImageId", getAdaptiveMediaImageId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("configurationUuid", getConfigurationUuid());
		attributes.put("fileVersionId", getFileVersionId());
		attributes.put("mimeType", getMimeType());
		attributes.put("height", getHeight());
		attributes.put("width", getWidth());
		attributes.put("size", getSize());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long adaptiveMediaImageId = (Long)attributes.get("adaptiveMediaImageId");

		if (adaptiveMediaImageId != null) {
			setAdaptiveMediaImageId(adaptiveMediaImageId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		String configurationUuid = (String)attributes.get("configurationUuid");

		if (configurationUuid != null) {
			setConfigurationUuid(configurationUuid);
		}

		Long fileVersionId = (Long)attributes.get("fileVersionId");

		if (fileVersionId != null) {
			setFileVersionId(fileVersionId);
		}

		String mimeType = (String)attributes.get("mimeType");

		if (mimeType != null) {
			setMimeType(mimeType);
		}

		Integer height = (Integer)attributes.get("height");

		if (height != null) {
			setHeight(height);
		}

		Integer width = (Integer)attributes.get("width");

		if (width != null) {
			setWidth(width);
		}

		Long size = (Long)attributes.get("size");

		if (size != null) {
			setSize(size);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getAdaptiveMediaImageId() {
		return _adaptiveMediaImageId;
	}

	@Override
	public void setAdaptiveMediaImageId(long adaptiveMediaImageId) {
		_adaptiveMediaImageId = adaptiveMediaImageId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public String getConfigurationUuid() {
		if (_configurationUuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _configurationUuid;
		}
	}

	@Override
	public void setConfigurationUuid(String configurationUuid) {
		_columnBitmask |= CONFIGURATIONUUID_COLUMN_BITMASK;

		if (_originalConfigurationUuid == null) {
			_originalConfigurationUuid = _configurationUuid;
		}

		_configurationUuid = configurationUuid;
	}

	public String getOriginalConfigurationUuid() {
		return GetterUtil.getString(_originalConfigurationUuid);
	}

	@Override
	public long getFileVersionId() {
		return _fileVersionId;
	}

	@Override
	public void setFileVersionId(long fileVersionId) {
		_columnBitmask |= FILEVERSIONID_COLUMN_BITMASK;

		if (!_setOriginalFileVersionId) {
			_setOriginalFileVersionId = true;

			_originalFileVersionId = _fileVersionId;
		}

		_fileVersionId = fileVersionId;
	}

	public long getOriginalFileVersionId() {
		return _originalFileVersionId;
	}

	@Override
	public String getMimeType() {
		if (_mimeType == null) {
			return StringPool.BLANK;
		}
		else {
			return _mimeType;
		}
	}

	@Override
	public void setMimeType(String mimeType) {
		_mimeType = mimeType;
	}

	@Override
	public int getHeight() {
		return _height;
	}

	@Override
	public void setHeight(int height) {
		_height = height;
	}

	@Override
	public int getWidth() {
		return _width;
	}

	@Override
	public void setWidth(int width) {
		_width = width;
	}

	@Override
	public long getSize() {
		return _size;
	}

	@Override
	public void setSize(long size) {
		_size = size;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			AdaptiveMediaImage.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AdaptiveMediaImage toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (AdaptiveMediaImage)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AdaptiveMediaImageImpl adaptiveMediaImageImpl = new AdaptiveMediaImageImpl();

		adaptiveMediaImageImpl.setUuid(getUuid());
		adaptiveMediaImageImpl.setAdaptiveMediaImageId(getAdaptiveMediaImageId());
		adaptiveMediaImageImpl.setGroupId(getGroupId());
		adaptiveMediaImageImpl.setCompanyId(getCompanyId());
		adaptiveMediaImageImpl.setCreateDate(getCreateDate());
		adaptiveMediaImageImpl.setConfigurationUuid(getConfigurationUuid());
		adaptiveMediaImageImpl.setFileVersionId(getFileVersionId());
		adaptiveMediaImageImpl.setMimeType(getMimeType());
		adaptiveMediaImageImpl.setHeight(getHeight());
		adaptiveMediaImageImpl.setWidth(getWidth());
		adaptiveMediaImageImpl.setSize(getSize());

		adaptiveMediaImageImpl.resetOriginalValues();

		return adaptiveMediaImageImpl;
	}

	@Override
	public int compareTo(AdaptiveMediaImage adaptiveMediaImage) {
		long primaryKey = adaptiveMediaImage.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof AdaptiveMediaImage)) {
			return false;
		}

		AdaptiveMediaImage adaptiveMediaImage = (AdaptiveMediaImage)obj;

		long primaryKey = adaptiveMediaImage.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AdaptiveMediaImageModelImpl adaptiveMediaImageModelImpl = this;

		adaptiveMediaImageModelImpl._originalUuid = adaptiveMediaImageModelImpl._uuid;

		adaptiveMediaImageModelImpl._originalGroupId = adaptiveMediaImageModelImpl._groupId;

		adaptiveMediaImageModelImpl._setOriginalGroupId = false;

		adaptiveMediaImageModelImpl._originalCompanyId = adaptiveMediaImageModelImpl._companyId;

		adaptiveMediaImageModelImpl._setOriginalCompanyId = false;

		adaptiveMediaImageModelImpl._originalConfigurationUuid = adaptiveMediaImageModelImpl._configurationUuid;

		adaptiveMediaImageModelImpl._originalFileVersionId = adaptiveMediaImageModelImpl._fileVersionId;

		adaptiveMediaImageModelImpl._setOriginalFileVersionId = false;

		adaptiveMediaImageModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<AdaptiveMediaImage> toCacheModel() {
		AdaptiveMediaImageCacheModel adaptiveMediaImageCacheModel = new AdaptiveMediaImageCacheModel();

		adaptiveMediaImageCacheModel.uuid = getUuid();

		String uuid = adaptiveMediaImageCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			adaptiveMediaImageCacheModel.uuid = null;
		}

		adaptiveMediaImageCacheModel.adaptiveMediaImageId = getAdaptiveMediaImageId();

		adaptiveMediaImageCacheModel.groupId = getGroupId();

		adaptiveMediaImageCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			adaptiveMediaImageCacheModel.createDate = createDate.getTime();
		}
		else {
			adaptiveMediaImageCacheModel.createDate = Long.MIN_VALUE;
		}

		adaptiveMediaImageCacheModel.configurationUuid = getConfigurationUuid();

		String configurationUuid = adaptiveMediaImageCacheModel.configurationUuid;

		if ((configurationUuid != null) && (configurationUuid.length() == 0)) {
			adaptiveMediaImageCacheModel.configurationUuid = null;
		}

		adaptiveMediaImageCacheModel.fileVersionId = getFileVersionId();

		adaptiveMediaImageCacheModel.mimeType = getMimeType();

		String mimeType = adaptiveMediaImageCacheModel.mimeType;

		if ((mimeType != null) && (mimeType.length() == 0)) {
			adaptiveMediaImageCacheModel.mimeType = null;
		}

		adaptiveMediaImageCacheModel.height = getHeight();

		adaptiveMediaImageCacheModel.width = getWidth();

		adaptiveMediaImageCacheModel.size = getSize();

		return adaptiveMediaImageCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", adaptiveMediaImageId=");
		sb.append(getAdaptiveMediaImageId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", configurationUuid=");
		sb.append(getConfigurationUuid());
		sb.append(", fileVersionId=");
		sb.append(getFileVersionId());
		sb.append(", mimeType=");
		sb.append(getMimeType());
		sb.append(", height=");
		sb.append(getHeight());
		sb.append(", width=");
		sb.append(getWidth());
		sb.append(", size=");
		sb.append(getSize());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.adaptive.media.image.model.AdaptiveMediaImage");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>adaptiveMediaImageId</column-name><column-value><![CDATA[");
		sb.append(getAdaptiveMediaImageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>configurationUuid</column-name><column-value><![CDATA[");
		sb.append(getConfigurationUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fileVersionId</column-name><column-value><![CDATA[");
		sb.append(getFileVersionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mimeType</column-name><column-value><![CDATA[");
		sb.append(getMimeType());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>height</column-name><column-value><![CDATA[");
		sb.append(getHeight());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>width</column-name><column-value><![CDATA[");
		sb.append(getWidth());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>size</column-name><column-value><![CDATA[");
		sb.append(getSize());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = AdaptiveMediaImage.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			AdaptiveMediaImage.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _adaptiveMediaImageId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private Date _createDate;
	private String _configurationUuid;
	private String _originalConfigurationUuid;
	private long _fileVersionId;
	private long _originalFileVersionId;
	private boolean _setOriginalFileVersionId;
	private String _mimeType;
	private int _height;
	private int _width;
	private long _size;
	private long _columnBitmask;
	private AdaptiveMediaImage _escapedModel;
}