<definition>
	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="DATA_DEFINITION_MENULIST_DELETE">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
		<case locator-key1="DATA_DEFINITION_MENULIST_EDIT">
			<execute function="Click#textClickAtAndWait" value1="Edit" />
		</case>
		<case comparator="startsWith" locator-key1="DATA_DEFINITION_TABLE_ACTIONS_">
			<execute function="Click#pauseTextClickAt" value1="Actions" />
		</case>
		<case locator-key1="TOOLBAR_ADD">
			<execute function="Click#textClickAtAndWait" value1="Add" />
		</case>
		<case locator-key1="TOOLBAR_SEARCH_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Search" />
		</case>
	</command>
</definition>