<definition>
	<command name="click">
		<case locator-key1="DETAILS">
			<execute function="Click#textClickAt" value1="Details" />
		</case>
		<case locator-key1="FIELDS_LINK">
			<execute function="Click#textClickAt" value1="Fields" />
		</case>
		<case locator-key1="SAVE_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Save" />
		</case>
		<case locator-key1="SETTINGS_CELL_EDITOR_SAVE_BUTTON">
			<execute function="Click#textClickAt" value1="Save" />
		</case>
	</command>

	<command name="isElementNotPresent">
		<case locator-key1="DETAILS_DESCRIPTION_FIELD">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="DETAILS_DESCRIPTION_FIELD">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="DETAILS_DESCRIPTION_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>
		<case locator-key1="NAME_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>