<definition>
	<command name="assertTextEquals">
		<case locator-key1="INFO_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="assertClick">
		<case locator-key1="ADD_RECORD_BUTTON">
			<execute function="AssertClick#assertPartialTextClickAtAndWait" />
		</case>

		<case locator-key1="RECORD_MENULIST_DELETE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="RECORD_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="RECORD_MENULIST_VIEW">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case comparator="startsWith" locator-key1="RECORD_TABLE_ACTIONS_">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
	</command>
</definition>