<definition>
	<command name="assertClick">
		<case locator-key1="SAVE_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="DATA_LIST_RECORD_FIELDS_TEXT">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="HEADER_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>