<definition>
	<command name="assertTextEquals">
		<case locator-key1="DATA_DEFINITION_NAME">
			<execute function="AssertTextEquals#assertValue" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="DESCRIPTION_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="NAME_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>