<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="TEMPLATE_TABLE_ACTIONS_">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>

		<case locator-key1="TOOLBAR_ADD_FORM_TEMPLATE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>