<definition>
	<command name="assertClick">
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
		<case locator-key1="LIST_MENULIST_DELETE">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
		<case locator-key1="LIST_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="LIST_MENULIST_SPREADSHEET_VIEW">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="LIST_TABLE_NAME">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="LIST_TABLE_ACTIONS">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
		<case locator-key1="TOOLBAR_ADD">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="TOOLBAR_MANAGE_DATA_DEFINITIONS">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
	</command>
</definition>