<definition>
	<command name="assertClick">
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
		<case comparator="startsWith" locator-key1="DATA_DEFINITION_TABLE_NAME">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
	</command>
</definition>