/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.friendly.url.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FriendlyURL service. Represents a row in the &quot;FriendlyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.friendly.url.model.impl.FriendlyURLModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.friendly.url.model.impl.FriendlyURLImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FriendlyURL
 * @see com.liferay.friendly.url.model.impl.FriendlyURLImpl
 * @see com.liferay.friendly.url.model.impl.FriendlyURLModelImpl
 * @generated
 */
@ProviderType
public interface FriendlyURLModel extends AttachedModel, BaseModel<FriendlyURL>,
	ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a friendly u r l model instance should use the {@link FriendlyURL} interface instead.
	 */

	/**
	 * Returns the primary key of this friendly u r l.
	 *
	 * @return the primary key of this friendly u r l
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this friendly u r l.
	 *
	 * @param primaryKey the primary key of this friendly u r l
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this friendly u r l.
	 *
	 * @return the uuid of this friendly u r l
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this friendly u r l.
	 *
	 * @param uuid the uuid of this friendly u r l
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the friendly u r l ID of this friendly u r l.
	 *
	 * @return the friendly u r l ID of this friendly u r l
	 */
	public long getFriendlyURLId();

	/**
	 * Sets the friendly u r l ID of this friendly u r l.
	 *
	 * @param friendlyURLId the friendly u r l ID of this friendly u r l
	 */
	public void setFriendlyURLId(long friendlyURLId);

	/**
	 * Returns the group ID of this friendly u r l.
	 *
	 * @return the group ID of this friendly u r l
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this friendly u r l.
	 *
	 * @param groupId the group ID of this friendly u r l
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this friendly u r l.
	 *
	 * @return the company ID of this friendly u r l
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this friendly u r l.
	 *
	 * @param companyId the company ID of this friendly u r l
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this friendly u r l.
	 *
	 * @return the create date of this friendly u r l
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this friendly u r l.
	 *
	 * @param createDate the create date of this friendly u r l
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this friendly u r l.
	 *
	 * @return the modified date of this friendly u r l
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this friendly u r l.
	 *
	 * @param modifiedDate the modified date of this friendly u r l
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this friendly u r l.
	 *
	 * @return the fully qualified class name of this friendly u r l
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this friendly u r l.
	 *
	 * @return the class name ID of this friendly u r l
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this friendly u r l.
	 *
	 * @param classNameId the class name ID of this friendly u r l
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this friendly u r l.
	 *
	 * @return the class p k of this friendly u r l
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this friendly u r l.
	 *
	 * @param classPK the class p k of this friendly u r l
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the url title of this friendly u r l.
	 *
	 * @return the url title of this friendly u r l
	 */
	@AutoEscape
	public String getUrlTitle();

	/**
	 * Sets the url title of this friendly u r l.
	 *
	 * @param urlTitle the url title of this friendly u r l
	 */
	public void setUrlTitle(String urlTitle);

	/**
	 * Returns the main of this friendly u r l.
	 *
	 * @return the main of this friendly u r l
	 */
	public boolean getMain();

	/**
	 * Returns <code>true</code> if this friendly u r l is main.
	 *
	 * @return <code>true</code> if this friendly u r l is main; <code>false</code> otherwise
	 */
	public boolean isMain();

	/**
	 * Sets whether this friendly u r l is main.
	 *
	 * @param main the main of this friendly u r l
	 */
	public void setMain(boolean main);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FriendlyURL friendlyURL);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FriendlyURL> toCacheModel();

	@Override
	public FriendlyURL toEscapedModel();

	@Override
	public FriendlyURL toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}