<definition>
	<command name="assertClick">
		<case locator-key1="AVAILABLE_SITES">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="JOIN_SITE_NAME">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="LEAVE_SITE_NAME">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>