/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.forms.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the FormsStructureEntryLink service. Represents a row in the &quot;FormsStructureEntryLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.forms.model.impl.FormsStructureEntryLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.forms.model.impl.FormsStructureEntryLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FormsStructureEntryLink
 * @see com.liferay.portlet.forms.model.impl.FormsStructureEntryLinkImpl
 * @see com.liferay.portlet.forms.model.impl.FormsStructureEntryLinkModelImpl
 * @generated
 */
public interface FormsStructureEntryLinkModel extends BaseModel<FormsStructureEntryLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a forms structure entry link model instance should use the {@link FormsStructureEntryLink} interface instead.
	 */

	/**
	 * Gets the primary key of this forms structure entry link.
	 *
	 * @return the primary key of this forms structure entry link
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this forms structure entry link
	 *
	 * @param pk the primary key of this forms structure entry link
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the form structure link ID of this forms structure entry link.
	 *
	 * @return the form structure link ID of this forms structure entry link
	 */
	public long getFormStructureLinkId();

	/**
	 * Sets the form structure link ID of this forms structure entry link.
	 *
	 * @param formStructureLinkId the form structure link ID of this forms structure entry link
	 */
	public void setFormStructureLinkId(long formStructureLinkId);

	/**
	 * Gets the form structure ID of this forms structure entry link.
	 *
	 * @return the form structure ID of this forms structure entry link
	 */
	@AutoEscape
	public String getFormStructureId();

	/**
	 * Sets the form structure ID of this forms structure entry link.
	 *
	 * @param formStructureId the form structure ID of this forms structure entry link
	 */
	public void setFormStructureId(String formStructureId);

	/**
	 * Gets the class name of this forms structure entry link.
	 *
	 * @return the class name of this forms structure entry link
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this forms structure entry link.
	 *
	 * @param className the class name of this forms structure entry link
	 */
	public void setClassName(String className);

	/**
	 * Gets the class p k of this forms structure entry link.
	 *
	 * @return the class p k of this forms structure entry link
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this forms structure entry link.
	 *
	 * @param classPK the class p k of this forms structure entry link
	 */
	public void setClassPK(long classPK);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(FormsStructureEntryLink formsStructureEntryLink);

	public int hashCode();

	public FormsStructureEntryLink toEscapedModel();

	public String toString();

	public String toXmlString();
}