<definition>
	<command name="assertTextEquals">
		<case locator-key1="DEFAULT_USER_ASSOCIATIONS_SITES_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="DEFAULT_USER_ASSOCIATIONS_ORGANIZATION_SITES_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="DEFAULT_USER_ASSOCIATIONS_ROLES_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="DEFAULT_USER_ASSOCIATIONS_ROLES_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="DEFAULT_USER_ASSOCIATIONS_USER_GROUPS_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="RESERVED_CREDENTIALS_EMAIL_ADDRESSES_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="RESERVED_CREDENTIALS_SCREEN_NAMES_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>