<definition>
	<command name="assertTextEquals">
		<case locator-key1="EMAIL_NOTIFICATIONS_ACCOUNT_CREATED_NOTIFICATION_BODY_WITH_PASSWORD_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="EMAIL_NOTIFICATIONS_ACCOUNT_CREATED_NOTIFICATION_BODY_WITHOUT_PASSWORD_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>