<definition>
	<command name="assertTextEquals">
		<case locator-key1="EMAIL_NOTIFICATIONS_ACCOUNT_CREATED_NOTIFICATION_BODY_WITH_PASSWORD_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="EMAIL_NOTIFICATIONS_ACCOUNT_CREATED_NOTIFICATION_BODY_WITHOUT_PASSWORD_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="EMAIL_NOTIFICATIONS_PASSWORD_CHANGED_NOTIFICATION_BODY_HEADER">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="EMAIL_NOTIFICATIONS_ACCOUNT_CREATED_NOTIFICATION_BODY_WITH_PASSWORD">
			<execute function="Type#typeFrame" />
		</case>

		<case locator-key1="NAVIGATION_EMAIL_VERIFICATiON_NOTIFICATION_BODY">
			<execute function="Type#typeFrame" />
		</case>
	</command>
</definition>