/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the LayoutFriendlyURL service. Represents a row in the &quot;LayoutFriendlyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.LayoutFriendlyURLModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.LayoutFriendlyURLImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutFriendlyURL
 * @see com.liferay.portal.model.impl.LayoutFriendlyURLImpl
 * @see com.liferay.portal.model.impl.LayoutFriendlyURLModelImpl
 * @generated
 */
public interface LayoutFriendlyURLModel extends BaseModel<LayoutFriendlyURL> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout friendly u r l model instance should use the {@link LayoutFriendlyURL} interface instead.
	 */

	/**
	 * Returns the primary key of this layout friendly u r l.
	 *
	 * @return the primary key of this layout friendly u r l
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout friendly u r l.
	 *
	 * @param primaryKey the primary key of this layout friendly u r l
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this layout friendly u r l.
	 *
	 * @return the uuid of this layout friendly u r l
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this layout friendly u r l.
	 *
	 * @param uuid the uuid of this layout friendly u r l
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the layout friendly u r l ID of this layout friendly u r l.
	 *
	 * @return the layout friendly u r l ID of this layout friendly u r l
	 */
	public long getLayoutFriendlyURLId();

	/**
	 * Sets the layout friendly u r l ID of this layout friendly u r l.
	 *
	 * @param layoutFriendlyURLId the layout friendly u r l ID of this layout friendly u r l
	 */
	public void setLayoutFriendlyURLId(long layoutFriendlyURLId);

	/**
	 * Returns the group ID of this layout friendly u r l.
	 *
	 * @return the group ID of this layout friendly u r l
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this layout friendly u r l.
	 *
	 * @param groupId the group ID of this layout friendly u r l
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this layout friendly u r l.
	 *
	 * @return the company ID of this layout friendly u r l
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this layout friendly u r l.
	 *
	 * @param companyId the company ID of this layout friendly u r l
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the plid of this layout friendly u r l.
	 *
	 * @return the plid of this layout friendly u r l
	 */
	public long getPlid();

	/**
	 * Sets the plid of this layout friendly u r l.
	 *
	 * @param plid the plid of this layout friendly u r l
	 */
	public void setPlid(long plid);

	/**
	 * Returns the private layout of this layout friendly u r l.
	 *
	 * @return the private layout of this layout friendly u r l
	 */
	public boolean getPrivateLayout();

	/**
	 * Returns <code>true</code> if this layout friendly u r l is private layout.
	 *
	 * @return <code>true</code> if this layout friendly u r l is private layout; <code>false</code> otherwise
	 */
	public boolean isPrivateLayout();

	/**
	 * Sets whether this layout friendly u r l is private layout.
	 *
	 * @param privateLayout the private layout of this layout friendly u r l
	 */
	public void setPrivateLayout(boolean privateLayout);

	/**
	 * Returns the friendly u r l of this layout friendly u r l.
	 *
	 * @return the friendly u r l of this layout friendly u r l
	 */
	@AutoEscape
	public String getFriendlyURL();

	/**
	 * Sets the friendly u r l of this layout friendly u r l.
	 *
	 * @param friendlyURL the friendly u r l of this layout friendly u r l
	 */
	public void setFriendlyURL(String friendlyURL);

	/**
	 * Returns the language ID of this layout friendly u r l.
	 *
	 * @return the language ID of this layout friendly u r l
	 */
	@AutoEscape
	public String getLanguageId();

	/**
	 * Sets the language ID of this layout friendly u r l.
	 *
	 * @param languageId the language ID of this layout friendly u r l
	 */
	public void setLanguageId(String languageId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LayoutFriendlyURL layoutFriendlyURL);

	public int hashCode();

	public CacheModel<LayoutFriendlyURL> toCacheModel();

	public LayoutFriendlyURL toEscapedModel();

	public LayoutFriendlyURL toUnescapedModel();

	public String toString();

	public String toXmlString();
}