/**
 * Copyright (c) 2000-2010 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LayoutRevision service. Represents a row in the &quot;LayoutRevision&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portal.model.impl.LayoutRevisionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portal.model.impl.LayoutRevisionImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LayoutRevision
 * @see com.liferay.portal.model.impl.LayoutRevisionImpl
 * @see com.liferay.portal.model.impl.LayoutRevisionModelImpl
 * @generated
 */
public interface LayoutRevisionModel extends BaseModel<LayoutRevision> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a layout revision model instance should use the {@link LayoutRevision} interface instead.
	 */

	/**
	 * Gets the primary key of this layout revision.
	 *
	 * @return the primary key of this layout revision
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this layout revision
	 *
	 * @param pk the primary key of this layout revision
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the layout revision id of this layout revision.
	 *
	 * @return the layout revision id of this layout revision
	 */
	public long getLayoutRevisionId();

	/**
	 * Sets the layout revision id of this layout revision.
	 *
	 * @param layoutRevisionId the layout revision id of this layout revision
	 */
	public void setLayoutRevisionId(long layoutRevisionId);

	/**
	 * Gets the group id of this layout revision.
	 *
	 * @return the group id of this layout revision
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this layout revision.
	 *
	 * @param groupId the group id of this layout revision
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company id of this layout revision.
	 *
	 * @return the company id of this layout revision
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this layout revision.
	 *
	 * @param companyId the company id of this layout revision
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user id of this layout revision.
	 *
	 * @return the user id of this layout revision
	 */
	public long getUserId();

	/**
	 * Sets the user id of this layout revision.
	 *
	 * @param userId the user id of this layout revision
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this layout revision.
	 *
	 * @return the user uuid of this layout revision
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this layout revision.
	 *
	 * @param userUuid the user uuid of this layout revision
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this layout revision.
	 *
	 * @return the user name of this layout revision
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this layout revision.
	 *
	 * @param userName the user name of this layout revision
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this layout revision.
	 *
	 * @return the create date of this layout revision
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this layout revision.
	 *
	 * @param createDate the create date of this layout revision
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this layout revision.
	 *
	 * @return the modified date of this layout revision
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this layout revision.
	 *
	 * @param modifiedDate the modified date of this layout revision
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the layout branch id of this layout revision.
	 *
	 * @return the layout branch id of this layout revision
	 */
	public long getLayoutBranchId();

	/**
	 * Sets the layout branch id of this layout revision.
	 *
	 * @param layoutBranchId the layout branch id of this layout revision
	 */
	public void setLayoutBranchId(long layoutBranchId);

	/**
	 * Gets the parent layout revision id of this layout revision.
	 *
	 * @return the parent layout revision id of this layout revision
	 */
	public long getParentLayoutRevisionId();

	/**
	 * Sets the parent layout revision id of this layout revision.
	 *
	 * @param parentLayoutRevisionId the parent layout revision id of this layout revision
	 */
	public void setParentLayoutRevisionId(long parentLayoutRevisionId);

	/**
	 * Gets the head of this layout revision.
	 *
	 * @return the head of this layout revision
	 */
	public boolean getHead();

	/**
	 * Determines if this layout revision is head.
	 *
	 * @return <code>true</code> if this layout revision is head; <code>false</code> otherwise
	 */
	public boolean isHead();

	/**
	 * Sets whether this layout revision is head.
	 *
	 * @param head the head of this layout revision
	 */
	public void setHead(boolean head);

	/**
	 * Gets the plid of this layout revision.
	 *
	 * @return the plid of this layout revision
	 */
	public long getPlid();

	/**
	 * Sets the plid of this layout revision.
	 *
	 * @param plid the plid of this layout revision
	 */
	public void setPlid(long plid);

	/**
	 * Gets the name of this layout revision.
	 *
	 * @return the name of this layout revision
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this layout revision.
	 *
	 * @param name the name of this layout revision
	 */
	public void setName(String name);

	/**
	 * Gets the title of this layout revision.
	 *
	 * @return the title of this layout revision
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this layout revision.
	 *
	 * @param title the title of this layout revision
	 */
	public void setTitle(String title);

	/**
	 * Gets the description of this layout revision.
	 *
	 * @return the description of this layout revision
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this layout revision.
	 *
	 * @param description the description of this layout revision
	 */
	public void setDescription(String description);

	/**
	 * Gets the type settings of this layout revision.
	 *
	 * @return the type settings of this layout revision
	 */
	@AutoEscape
	public String getTypeSettings();

	/**
	 * Sets the type settings of this layout revision.
	 *
	 * @param typeSettings the type settings of this layout revision
	 */
	public void setTypeSettings(String typeSettings);

	/**
	 * Gets the icon image of this layout revision.
	 *
	 * @return the icon image of this layout revision
	 */
	public boolean getIconImage();

	/**
	 * Determines if this layout revision is icon image.
	 *
	 * @return <code>true</code> if this layout revision is icon image; <code>false</code> otherwise
	 */
	public boolean isIconImage();

	/**
	 * Sets whether this layout revision is icon image.
	 *
	 * @param iconImage the icon image of this layout revision
	 */
	public void setIconImage(boolean iconImage);

	/**
	 * Gets the icon image id of this layout revision.
	 *
	 * @return the icon image id of this layout revision
	 */
	public long getIconImageId();

	/**
	 * Sets the icon image id of this layout revision.
	 *
	 * @param iconImageId the icon image id of this layout revision
	 */
	public void setIconImageId(long iconImageId);

	/**
	 * Gets the theme id of this layout revision.
	 *
	 * @return the theme id of this layout revision
	 */
	@AutoEscape
	public String getThemeId();

	/**
	 * Sets the theme id of this layout revision.
	 *
	 * @param themeId the theme id of this layout revision
	 */
	public void setThemeId(String themeId);

	/**
	 * Gets the color scheme id of this layout revision.
	 *
	 * @return the color scheme id of this layout revision
	 */
	@AutoEscape
	public String getColorSchemeId();

	/**
	 * Sets the color scheme id of this layout revision.
	 *
	 * @param colorSchemeId the color scheme id of this layout revision
	 */
	public void setColorSchemeId(String colorSchemeId);

	/**
	 * Gets the wap theme id of this layout revision.
	 *
	 * @return the wap theme id of this layout revision
	 */
	@AutoEscape
	public String getWapThemeId();

	/**
	 * Sets the wap theme id of this layout revision.
	 *
	 * @param wapThemeId the wap theme id of this layout revision
	 */
	public void setWapThemeId(String wapThemeId);

	/**
	 * Gets the wap color scheme id of this layout revision.
	 *
	 * @return the wap color scheme id of this layout revision
	 */
	@AutoEscape
	public String getWapColorSchemeId();

	/**
	 * Sets the wap color scheme id of this layout revision.
	 *
	 * @param wapColorSchemeId the wap color scheme id of this layout revision
	 */
	public void setWapColorSchemeId(String wapColorSchemeId);

	/**
	 * Gets the css of this layout revision.
	 *
	 * @return the css of this layout revision
	 */
	@AutoEscape
	public String getCss();

	/**
	 * Sets the css of this layout revision.
	 *
	 * @param css the css of this layout revision
	 */
	public void setCss(String css);

	/**
	 * Gets the status of this layout revision.
	 *
	 * @return the status of this layout revision
	 */
	public int getStatus();

	/**
	 * Sets the status of this layout revision.
	 *
	 * @param status the status of this layout revision
	 */
	public void setStatus(int status);

	/**
	 * Gets the status by user id of this layout revision.
	 *
	 * @return the status by user id of this layout revision
	 */
	public long getStatusByUserId();

	/**
	 * Sets the status by user id of this layout revision.
	 *
	 * @param statusByUserId the status by user id of this layout revision
	 */
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Gets the status by user uuid of this layout revision.
	 *
	 * @return the status by user uuid of this layout revision
	 * @throws SystemException if a system exception occurred
	 */
	public String getStatusByUserUuid() throws SystemException;

	/**
	 * Sets the status by user uuid of this layout revision.
	 *
	 * @param statusByUserUuid the status by user uuid of this layout revision
	 */
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Gets the status by user name of this layout revision.
	 *
	 * @return the status by user name of this layout revision
	 */
	@AutoEscape
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this layout revision.
	 *
	 * @param statusByUserName the status by user name of this layout revision
	 */
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Gets the status date of this layout revision.
	 *
	 * @return the status date of this layout revision
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this layout revision.
	 *
	 * @param statusDate the status date of this layout revision
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * @deprecated {@link #isApproved}
	 */
	public boolean getApproved();

	/**
	 * Determines if this layout revision is approved.
	 *
	 * @return <code>true</code> if this layout revision is approved; <code>false</code> otherwise
	 */
	public boolean isApproved();

	/**
	 * Determines if this layout revision is a draft.
	 *
	 * @return <code>true</code> if this layout revision is a draft; <code>false</code> otherwise
	 */
	public boolean isDraft();

	/**
	 * Determines if this layout revision is expired.
	 *
	 * @return <code>true</code> if this layout revision is expired; <code>false</code> otherwise
	 */
	public boolean isExpired();

	/**
	 * Determines if this layout revision is pending.
	 *
	 * @return <code>true</code> if this layout revision is pending; <code>false</code> otherwise
	 */
	public boolean isPending();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(LayoutRevision layoutRevision);

	public int hashCode();

	public LayoutRevision toEscapedModel();

	public String toString();

	public String toXmlString();
}