<definition>
	<command name="assertClick">
		<case locator-key1="PUBLISH_BUTTON">
			<execute function="AssertClick#assertTextClickAt" ignore-javascript-error="u is null" />
		</case>
	</command>
</definition>