<definition>
	<command name="assertClick">
		<case locator-key1="FIELDS_LINK">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SETTINGS_OPTIONS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>