<definition>
	<command name="assertElementNotPresent">
		<case locator-key1="RSS_OPTIONS">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="RSS_FEED_TITLE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>