<?xml version="1.0" encoding="UTF-8"?>

<javadoc autogenerated="true">
	<name>${entity.name}JSONSerializer</name>
	<type>${packagePath}.service.http.${entity.name}JSONSerializer</type>
	<comment>
		<![CDATA[
			<p>
				ServiceBuilder generated this class. Modifications in this class will be
				overwritten the next time is generated.
			</p>

			<p>
				This class is used by {@link ${entity.name}ServiceJSON} to translate
				objects.
			</p>
		]]>
	</comment>
	<author>${author}</author>
	<see>${entity.name}ServiceJSON</see>
</javadoc>