<definition>
	<command name="assertTextEquals">
		<case locator-key1="ENTRY_FILE_TABLE_SCHEDULED_FILE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>