<definition>
	<command name="assertTextEquals">
		<case locator-key1="INFO_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="No user groups were found." />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD">
			<execute function="Click#textClickAtAndWait" value1="Add" />
		</case>
		<case locator-key1="DELETE_BUTTON">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
		<case locator-key1="USER_GROUP_MENULIST_EDIT">
			<execute function="Click#textClickAtAndWait" value1="Edit" />
		</case>
		<case locator-key1="USER_GROUP_MENULIST_DELETE">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
		<case locator-key1="USER_GROUP_TABLE_ACTIONS_1">
			<execute function="Click#textClickAt" value1="Actions" />
		</case>
	</command>
</definition>