<definition>
	<command name="assertClick">
		<case locator-key1="ADD">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="DELETE_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
		<case locator-key1="USER_GROUP_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="USER_GROUP_MENULIST_DELETE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="isElementPresent">
		<case comparator="startsWith" locator-key1="USER_GROUP_TABLE_CHECKBOX_">
			<execute function="IsElementPresent#pauseIsElementPresent" />
		</case>
	</command>
</definition>