<definition>
	<command name="assertTextEquals">
		<case locator-key1="ADMINISTRATOR_USER_EMAIL_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="ADMINISTRATOR_USER_FIRST_NAME_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="ADMINISTRATOR_USER_LAST_NAME_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="DATABASE_CHANGE_DATABASE_TYPE_LABEL">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="DATABASE_CHANGE_JDBC_DRIVER_CLASS_NAME_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="DATABASE_CHANGE_JDBC_DRIVER_CLASS_NAME_LABEL">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="DATABASE_CHANGE_PASSWORD_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="DATABASE_CHANGE_PASSWORD_LABEL">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="DATABASE_CHANGE_JDBC_URL_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="DATABASE_CHANGE_JDBC_URL_LABEL">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="DATABASE_CHANGE_USER_NAME_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>

		<case locator-key1="DATABASE_CHANGE_USER_NAME_LABEL">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="DATABASE_CONFIGURED_JDBC_DRIVER_CLASS_NAME_LABEL">
			<execute function="AssertTextEquals#assertText" />
		</case>

		<case locator-key1="PORTAL_PORTAL_NAME_FIELD">
			<execute function="AssertTextEquals#assertValue" />
		</case>
	</command>
</definition>