<definition>
	<command name="isElementNotPresent">
		<case locator-key1="DETAILS_DESCRIPTION_FIELD">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>

		<case locator-key1="DETAILS_MODE_SELECT">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>

	<command name="isElementPresent">
		<case locator-key1="DETAILS_DESCRIPTION_FIELD">
			<execute function="IsElementPresent#isVisible" />
		</case>

		<case locator-key1="DETAILS_MODE_SELECT">
			<execute function="IsElementPresent#isVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="DETAILS_DESCRIPTION_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="NAME_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>