<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="RECORD_TABLE_ACTIONS_">
			<execute function="AssertClick#assertTextClickAt" />
		</case>
		<case comparator="startsWith" locator-key1="RECORD_MENULIST_">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD_RECORD_BUTTON">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="TOOLBAR_ADD_LIST">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case locator-key1="TOOLBAR_SELECT_LIST">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>
</definition>