<definition>
	<command name="isElementNotPresent">
		<case locator-key1="DESCRIPTION_FIELD">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="NAME_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>
	</command>
</definition>