<definition>
	<command name="assertClick">
		<case locator-key1="MENU_CONTENT">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="MENU_PERMISSIONS">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="CONTENT_FIELD">
			<execute function="AssertTextEquals#assertCKEditorText" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrame" />
		</case>

		<case locator-key1="HTML_FIELD">
			<execute function="Type#typeFrame" />
		</case>
	</command>
</definition>