<definition>
	<command name="type">
		<case locator-key1="TITLE_FIELD">
			<execute function="Type#clickAtSendKeys" />
		</case>

		<case locator-key1="CONTENT_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>
	</command>
</definition>