<action-definition>
	<action-command name="AssertElementNotPresent">
		<default>
			<execute function="AssertElementNotPresent#assertElementNotPresent" />
		</default>
	</action-command>

	<action-command name="Click">
		<case comparator="contains" locator="/input">
			<execute function="Click#clickAtAndWait" />
		</case>
		<default>
			<execute function="Click#clickAt" />
		</default>
	</action-command>

	<action-command name="Confirm">
		<default>
			<execute function="Confirm#assertConfirmation" />
		</default>
	</action-command>

	<action-command name="DragAndDrop">
		<default>
			<execute function="DragAndDrop#dragAndDrop" />
		</default>
	</action-command>
</action-definition>