<definition>
	<command name="assertClick">
		<case locator-key1="GMAIL_HTML_MODE_MAIL_TABLE_MESSAGE_TITLE">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="GMAIL_HTML_MODE_MESSAGE_BODY_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="GMAIL_HTML_MODE_MAIL_TABLE_USER_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="GMAIL_HTML_MODE_MESSAGE_BODY">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="GMAIL_HTML_MODE_MESSAGE_BODY_CLOSING">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="GMAIL_HTML_MODE_MESSAGE_BODY_GREETING">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="close">
		<default>
			<execute function="Close#closeWindow" />
		</default>
	</command>
</definition>