<definition>
	<command name="assertClick">
		<case comparator="startsWith" locator-key1="CONTROL_PANEL_">
			<execute function="AssertClick#assertPartialTextClickAtCPNavigation" />
		</case>

		<case comparator="startsWith" locator-key1="SITE_ADMINISTRATION_">
			<execute function="AssertClick#assertPartialTextClickAtCPNavigation" />
		</case>

		<case comparator="startsWith" locator1="link" >
			<execute function="AssertClick#assertTextClickAtNavigation" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="PAGE_DELETE">
			<execute function="Click#click" />
		</case>

		<case comparator="startsWith" locator1="//ul[@class='nav control-panel-bar-secondary nav-pills']//a[contains(.,">
			<execute function="Click#clickAtAndWait" />
		</case>

		<case comparator="startsWith" locator1="link" >
			<execute function="Click#clickAtNavigation" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="PAGE_CONFIRM">
			<execute function="Confirm#waitForConfirmation" />
		</case>
	</command>

	<command name="mouseOver">
		<case comparator="startsWith" locator-key1="PAGE_">
			<execute function="MouseOver#mouseOverClickNavigation" />
		</case>
	</command>

	<command name="isElementPresent">
		<case comparator="startsWith" locator-key1="CONTROL_PANEL_">
			<execute function="IsElementPresent#isElementPresentCPNavigation" />
		</case>

		<case comparator="startsWith" locator-key1="PAGE_">
			<execute function="IsElementPresent#isElementPresentClickNavigation" />
		</case>
	</command>
</definition>