<definition>
	<command name="click">
		<case comparator="startsWith" locator-key1="PAGE_DELETE">
			<execute function="Click#textClick" value1="X" />
		</case>
		<case comparator="startsWith" locator1="link=">
			<execute function="Click#clickAtAndWait" />
		</case>
		<case comparator="startsWith" locator1="//a[@role='menuitem' and contains(.,">
			<execute function="Click#clickAtAndWait" />
		</case>
	</command>

	<command name="confirm">
		<case locator-key1="PAGE_CONFIRM">
			<execute function="Confirm#waitForConfirmation" />
		</case>
	</command>

	<command name="isElementPresent">
		<case comparator="startsWith" locator-key1="PAGE_">
			<execute function="IsElementPresent#isElementPresentClickNavigation" />
		</case>
	</command>
</definition>