<definition>
	<command name="assertClick">
		<case locator-key1="PUBLISH_BUTTON">
			<execute function="AssertClick#assertValueClickAtAndWait" />
		</case>
		<case locator-key1="SELECT_DOCUMENT_TYPE_BASIC_DOCUMENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="selectFrame">
		<case locator-key1="SELECT_DOCUMENT_TYPE_IFRAME">
			<execute function="SelectFrame#selectFrameWaitForScript" />
		</case>
	</command>
</definition>