<definition>
	<command name="assertClick">
		<case locator-key1="ADD_WEB_CONTENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="EDIT_WEB_CONTENT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>