<definition>
	<command name="assertClick">
		<case locator-key1="NAVIGATION_COMPLETED">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="PENDING_TABLE_ASSET_TITLE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="PENDING_TABLE_WITHDRAW_SUBMISSION">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>