<definition>
	<command name="assertClick">
		<case locator-key1="ADD_SITE_PAGES_VARIATIONS_BUTTON">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>

		<case locator-key1="EDIT_SITE_PAGES_VARIATION_UPDATE_BUTTON">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>
	</command>
</definition>