<definition>
	<command name="assertClick">
		<case locator-key1="ADD_PAGE_VARIATION_BUTTON">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>

		<case locator-key1="ADD_PAGE_VARIATION_ADD_BUTTON">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>
	</command>
</definition>