<definition>
	<command name="assertClick">
		<case locator-key1="STAGING_DROP_DOWN_BUTTON">
			<execute function="AssertClick#assertTextClickAtClickDockbar" />
		</case>

		<case locator-key1="STAGING_MENULIST_MANAGE_SITE_PAGES_VARIATIONS">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>

		<case locator-key1="STAGING_MENU_MANAGE_PAGE_VARIATION">
			<execute function="AssertClick#assertTextClickAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SITE_PAGES_VARIATION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="STAGING_MENU_REVISION_DETAILS_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="LIVE_MENU_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="isElementNotPresent">
		<case locator-key1="STAGING_MENULIST_PUBLISH_TO_LIVE_NOW">
			<execute function="IsElementNotPresent#isNotVisible" />
		</case>
	</command>
</definition>