<definition>
	<command name="assertClick">
		<case locator-key1="CURRENT_AND_PREVIOUS_DOWNLOAD">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="CURRENT_AND_PREVIOUS_DOWNLOAD">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="EXPORT_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>