<definition>
	<command name="assertChecked">
		<case locator-key1="DETAILS_PAGE_TYPE_PANEL_CHECKBOX_INPUT">
			<execute function="AssertChecked#waitForElementPresentAssertChecked" />
		</case>
	</command>

	<command name="assertElementPresent">
		<case locator-key1="PAGE_TREE_PAGE_LINK_1">
			<execute function="AssertElementPresent#assertElementPresent" />
		</case>

		<case locator-key1="PAGE_TREE_PAGE_LINK_2">
			<execute function="AssertElementPresent#assertElementPresent" />
		</case>

		<case locator-key1="PAGE_TREE_PAGE_LINK_3">
			<execute function="AssertElementPresent#assertElementPresent" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="INCOMPLETE_STAGING_PAGE_VARIATION_INFO_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="close">
		<default>
			<execute function="Close#closeWindow" />
		</default>
	</command>
</definition>