<definition>
	<command name="assertClick">
		<case locator-key1="ADD">
			<execute function="AssertClick#waitForNodeScriptAssertTextEqualsClick" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="PENCIL_ICON">
			<execute function="Click#waitForNavigationInteractionTouchScriptTap" />
		</case>

		<case locator-key1="REORDER_ICON">
			<execute function="Click#waitForNavigationInteractionTouchScriptTap" />
		</case>
	</command>
</definition>