<definition>
	<command name="assertClick">
		<case locator-key1="CONTACTS_LIST_NAME">
			<execute function="AssertClick#pauseAssertTextClickAt" />
		</case>

		<case locator-key1="CONTACTS_LIST_VIEW_MORE">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="CONNECT_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="DISCONNECT_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="FOLLOW_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="UNFOLLOW_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="BLOCK_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="UNBLOCK_BUTTON">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>

		<case locator-key1="BLOCKED_MESSAGE">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>

	<command name="type">
		<case locator-key1="CONTACTS_LIST_SEARCH">
			<execute function="Type#typePause" />
		</case>
	</command>
</definition>