<definition>
	<command name="assertClick">
		<case locator-key1="POLLS_QUESTION_CHOICE">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="POLLS_QUESTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>

	<command name="click">
		<case locator-key1="SELECT_QUESTION">
			<execute function="Click#makeVisibleClickAt" />
		</case>
	</command>
</definition>