<definition>
	<command name="assertClick">
		<case locator-key1="NOTIFICATIONS_LIST_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>

		<case locator-key1="REQUESTS_LIST_LINK">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>
</definition>