<definition>
	<command name="assertTextEquals">
		<case locator-key1="FOLDERS_TABLE_FOLDER_DESCRIPTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SEARCH_TABLE_ENTRY_NAME">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SUCCESS_MESSAGE_RECYCLE_BIN">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>