<definition>
	<command name="assertTextEquals">
		<case locator-key1="AVAILABLE_FILE_TYPES_SELECT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="CURRENT_FILE_TYPES_SELECT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>