<definition>
	<command name="assertClick">
		<case locator-key1="BE_THE_FIRST">
			<execute function="AssertClick#assertPartialTextClickAt" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case comparator="startsWith" locator-key1="DOCUMENT_CONVERSION_">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="NO_COMMENTS_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PAGINATION_PAGES">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="PRINT_WEB_CONTENT">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="RELATED_ASSETS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SUBCRIBE_TO_COMMENTS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="UNSUBCRIBE_FROM_COMMENTS">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>