/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.dynamicdatamapping.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the DDMListEntry service. Represents a row in the &quot;DDMListEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMListEntry
 * @see com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryImpl
 * @see com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryModelImpl
 * @generated
 */
public interface DDMListEntryModel extends BaseModel<DDMListEntry>, GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d d m list entry model instance should use the {@link DDMListEntry} interface instead.
	 */

	/**
	 * Gets the primary key of this d d m list entry.
	 *
	 * @return the primary key of this d d m list entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d d m list entry
	 *
	 * @param pk the primary key of this d d m list entry
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this d d m list entry.
	 *
	 * @return the uuid of this d d m list entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this d d m list entry.
	 *
	 * @param uuid the uuid of this d d m list entry
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the list entry ID of this d d m list entry.
	 *
	 * @return the list entry ID of this d d m list entry
	 */
	public long getListEntryId();

	/**
	 * Sets the list entry ID of this d d m list entry.
	 *
	 * @param listEntryId the list entry ID of this d d m list entry
	 */
	public void setListEntryId(long listEntryId);

	/**
	 * Gets the group ID of this d d m list entry.
	 *
	 * @return the group ID of this d d m list entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this d d m list entry.
	 *
	 * @param groupId the group ID of this d d m list entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the company ID of this d d m list entry.
	 *
	 * @return the company ID of this d d m list entry
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this d d m list entry.
	 *
	 * @param companyId the company ID of this d d m list entry
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the user ID of this d d m list entry.
	 *
	 * @return the user ID of this d d m list entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this d d m list entry.
	 *
	 * @param userId the user ID of this d d m list entry
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this d d m list entry.
	 *
	 * @return the user uuid of this d d m list entry
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this d d m list entry.
	 *
	 * @param userUuid the user uuid of this d d m list entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the user name of this d d m list entry.
	 *
	 * @return the user name of this d d m list entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this d d m list entry.
	 *
	 * @param userName the user name of this d d m list entry
	 */
	public void setUserName(String userName);

	/**
	 * Gets the create date of this d d m list entry.
	 *
	 * @return the create date of this d d m list entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this d d m list entry.
	 *
	 * @param createDate the create date of this d d m list entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Gets the modified date of this d d m list entry.
	 *
	 * @return the modified date of this d d m list entry
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this d d m list entry.
	 *
	 * @param modifiedDate the modified date of this d d m list entry
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the name of this d d m list entry.
	 *
	 * @return the name of this d d m list entry
	 */
	public String getName();

	/**
	 * Gets the localized name of this d d m list entry. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale to get the localized name for
	 * @return the localized name of this d d m list entry
	 */
	public String getName(Locale locale);

	/**
	 * Gets the localized name of this d d m list entry, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local to get the localized name for
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this d d m list entry. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	public String getName(Locale locale, boolean useDefault);

	/**
	 * Gets the localized name of this d d m list entry. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the id of the language to get the localized name for
	 * @return the localized name of this d d m list entry
	 */
	public String getName(String languageId);

	/**
	 * Gets the localized name of this d d m list entry, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the id of the language to get the localized name for
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized name of this d d m list entry
	 */
	public String getName(String languageId, boolean useDefault);

	/**
	 * Gets a map of the locales and localized name of this d d m list entry.
	 *
	 * @return the locales and localized name
	 */
	public Map<Locale, String> getNameMap();

	/**
	 * Sets the name of this d d m list entry.
	 *
	 * @param name the name of this d d m list entry
	 */
	public void setName(String name);

	/**
	 * Sets the localized name of this d d m list entry.
	 *
	 * @param name the localized name of this d d m list entry
	 * @param locale the locale to set the localized name for
	 */
	public void setName(String name, Locale locale);

	public void setName(String name, Locale locale, Locale defaultLocale);

	/**
	 * Sets the localized names of this d d m list entry from the map of locales and localized names.
	 *
	 * @param nameMap the locales and localized names of this d d m list entry
	 */
	public void setNameMap(Map<Locale, String> nameMap);

	public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

	/**
	 * Gets the description of this d d m list entry.
	 *
	 * @return the description of this d d m list entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this d d m list entry.
	 *
	 * @param description the description of this d d m list entry
	 */
	public void setDescription(String description);

	/**
	 * Gets the structure ID of this d d m list entry.
	 *
	 * @return the structure ID of this d d m list entry
	 */
	public long getStructureId();

	/**
	 * Sets the structure ID of this d d m list entry.
	 *
	 * @param structureId the structure ID of this d d m list entry
	 */
	public void setStructureId(long structureId);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DDMListEntry ddmListEntry);

	public int hashCode();

	public DDMListEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}