/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.dynamicdatamapping.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the DDMListEntry service. Represents a row in the &quot;DDMListEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMListEntry
 * @see com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryImpl
 * @see com.liferay.portlet.dynamicdatamapping.model.impl.DDMListEntryModelImpl
 * @generated
 */
public interface DDMListEntryModel extends BaseModel<DDMListEntry> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a d d m list entry model instance should use the {@link DDMListEntry} interface instead.
	 */

	/**
	 * Gets the primary key of this d d m list entry.
	 *
	 * @return the primary key of this d d m list entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this d d m list entry
	 *
	 * @param pk the primary key of this d d m list entry
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the uuid of this d d m list entry.
	 *
	 * @return the uuid of this d d m list entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this d d m list entry.
	 *
	 * @param uuid the uuid of this d d m list entry
	 */
	public void setUuid(String uuid);

	/**
	 * Gets the list entry ID of this d d m list entry.
	 *
	 * @return the list entry ID of this d d m list entry
	 */
	public long getListEntryId();

	/**
	 * Sets the list entry ID of this d d m list entry.
	 *
	 * @param listEntryId the list entry ID of this d d m list entry
	 */
	public void setListEntryId(long listEntryId);

	/**
	 * Gets the list ID of this d d m list entry.
	 *
	 * @return the list ID of this d d m list entry
	 */
	public long getListId();

	/**
	 * Sets the list ID of this d d m list entry.
	 *
	 * @param listId the list ID of this d d m list entry
	 */
	public void setListId(long listId);

	/**
	 * Gets the class p k of this d d m list entry.
	 *
	 * @return the class p k of this d d m list entry
	 */
	public long getClassPK();

	/**
	 * Sets the class p k of this d d m list entry.
	 *
	 * @param classPK the class p k of this d d m list entry
	 */
	public void setClassPK(long classPK);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(DDMListEntry ddmListEntry);

	public int hashCode();

	public DDMListEntry toEscapedModel();

	public String toString();

	public String toXmlString();
}