<definition>
	<command name="type">
		<case locator-key1="BODY_FIELD">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>

		<case locator-key1="BODY_FIELD_LOCALIZED">
			<execute function="Type#typeFrameWaitForCKEditor" />
		</case>

		<case locator-key1="BODY_FIELD_SOURCE_ON">
			<execute function="Type#type" />
		</case>
	</command>
</definition>