/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.forms.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;
import com.liferay.portlet.forms.model.FormsStructureEntryLink;
import com.liferay.portlet.forms.model.FormsStructureEntryLinkModel;
import com.liferay.portlet.forms.model.FormsStructureEntryLinkSoap;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the FormsStructureEntryLink service. Represents a row in the &quot;FormsStructureEntryLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portlet.forms.model.FormsStructureEntryLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link FormsStructureEntryLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FormsStructureEntryLinkImpl
 * @see com.liferay.portlet.forms.model.FormsStructureEntryLink
 * @see com.liferay.portlet.forms.model.FormsStructureEntryLinkModel
 * @generated
 */
public class FormsStructureEntryLinkModelImpl extends BaseModelImpl<FormsStructureEntryLink>
	implements FormsStructureEntryLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a forms structure entry link model instance should use the {@link com.liferay.portlet.forms.model.FormsStructureEntryLink} interface instead.
	 */
	public static final String TABLE_NAME = "FormsStructureEntryLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "structureEntryLinkId", Types.BIGINT },
			{ "structureId", Types.VARCHAR },
			{ "className", Types.VARCHAR },
			{ "classPK", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table FormsStructureEntryLink (structureEntryLinkId LONG not null primary key,structureId VARCHAR(75) null,className VARCHAR(75) null,classPK LONG)";
	public static final String TABLE_SQL_DROP = "drop table FormsStructureEntryLink";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portlet.forms.model.FormsStructureEntryLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portlet.forms.model.FormsStructureEntryLink"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static FormsStructureEntryLink toModel(
		FormsStructureEntryLinkSoap soapModel) {
		FormsStructureEntryLink model = new FormsStructureEntryLinkImpl();

		model.setStructureEntryLinkId(soapModel.getStructureEntryLinkId());
		model.setStructureId(soapModel.getStructureId());
		model.setClassName(soapModel.getClassName());
		model.setClassPK(soapModel.getClassPK());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<FormsStructureEntryLink> toModels(
		FormsStructureEntryLinkSoap[] soapModels) {
		List<FormsStructureEntryLink> models = new ArrayList<FormsStructureEntryLink>(soapModels.length);

		for (FormsStructureEntryLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portlet.forms.model.FormsStructureEntryLink"));

	public FormsStructureEntryLinkModelImpl() {
	}

	public long getPrimaryKey() {
		return _structureEntryLinkId;
	}

	public void setPrimaryKey(long pk) {
		setStructureEntryLinkId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_structureEntryLinkId);
	}

	public long getStructureEntryLinkId() {
		return _structureEntryLinkId;
	}

	public void setStructureEntryLinkId(long structureEntryLinkId) {
		_structureEntryLinkId = structureEntryLinkId;
	}

	public String getStructureId() {
		if (_structureId == null) {
			return StringPool.BLANK;
		}
		else {
			return _structureId;
		}
	}

	public void setStructureId(String structureId) {
		if (_originalStructureId == null) {
			_originalStructureId = _structureId;
		}

		_structureId = structureId;
	}

	public String getOriginalStructureId() {
		return GetterUtil.getString(_originalStructureId);
	}

	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	public void setClassName(String className) {
		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	public long getClassPK() {
		return _classPK;
	}

	public void setClassPK(long classPK) {
		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public FormsStructureEntryLink toEscapedModel() {
		if (isEscapedModel()) {
			return (FormsStructureEntryLink)this;
		}
		else {
			return (FormsStructureEntryLink)Proxy.newProxyInstance(FormsStructureEntryLink.class.getClassLoader(),
				new Class[] { FormsStructureEntryLink.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					FormsStructureEntryLink.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		FormsStructureEntryLinkImpl formsStructureEntryLinkImpl = new FormsStructureEntryLinkImpl();

		formsStructureEntryLinkImpl.setStructureEntryLinkId(getStructureEntryLinkId());

		formsStructureEntryLinkImpl.setStructureId(getStructureId());

		FormsStructureEntryLinkModelImpl formsStructureEntryLinkModelImpl = formsStructureEntryLinkImpl;

		formsStructureEntryLinkModelImpl._originalStructureId = formsStructureEntryLinkModelImpl._structureId;

		formsStructureEntryLinkImpl.setClassName(getClassName());

		formsStructureEntryLinkModelImpl._originalClassName = formsStructureEntryLinkModelImpl._className;

		formsStructureEntryLinkImpl.setClassPK(getClassPK());

		formsStructureEntryLinkModelImpl._originalClassPK = formsStructureEntryLinkModelImpl._classPK;

		formsStructureEntryLinkModelImpl._setOriginalClassPK = false;

		return formsStructureEntryLinkImpl;
	}

	public int compareTo(FormsStructureEntryLink formsStructureEntryLink) {
		long pk = formsStructureEntryLink.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		FormsStructureEntryLink formsStructureEntryLink = null;

		try {
			formsStructureEntryLink = (FormsStructureEntryLink)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = formsStructureEntryLink.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{structureEntryLinkId=");
		sb.append(getStructureEntryLinkId());
		sb.append(", structureId=");
		sb.append(getStructureId());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.liferay.portlet.forms.model.FormsStructureEntryLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>structureEntryLinkId</column-name><column-value><![CDATA[");
		sb.append(getStructureEntryLinkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>structureId</column-name><column-value><![CDATA[");
		sb.append(getStructureId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _structureEntryLinkId;
	private String _structureId;
	private String _originalStructureId;
	private String _className;
	private String _originalClassName;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private transient ExpandoBridge _expandoBridge;
}