<definition>
	<command name="assertTextEquals">
		<case locator-key1="FOLDERS_TABLE_FOLDER_DESCRIPTION">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>