/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.dynamicdatamapping.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink;
import com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLinkModel;
import com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLinkSoap;
import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.ArrayList;
import java.util.List;

/**
 * The base model implementation for the DDMStructureEntryLink service. Represents a row in the &quot;DDMStructureEntryLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLinkModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DDMStructureEntryLinkImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DDMStructureEntryLinkImpl
 * @see com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink
 * @see com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLinkModel
 * @generated
 */
public class DDMStructureEntryLinkModelImpl extends BaseModelImpl<DDMStructureEntryLink>
	implements DDMStructureEntryLinkModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a d d m structure entry link model instance should use the {@link com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink} interface instead.
	 */
	public static final String TABLE_NAME = "DDMStructureEntryLink";
	public static final Object[][] TABLE_COLUMNS = {
			{ "structureEntryLinkId", Types.BIGINT },
			{ "structureKey", Types.VARCHAR },
			{ "className", Types.VARCHAR },
			{ "classPK", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table DDMStructureEntryLink (structureEntryLinkId LONG not null primary key,structureKey VARCHAR(75) null,className VARCHAR(75) null,classPK LONG)";
	public static final String TABLE_SQL_DROP = "drop table DDMStructureEntryLink";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.portal.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink"),
			true);

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DDMStructureEntryLink toModel(
		DDMStructureEntryLinkSoap soapModel) {
		DDMStructureEntryLink model = new DDMStructureEntryLinkImpl();

		model.setStructureEntryLinkId(soapModel.getStructureEntryLinkId());
		model.setStructureKey(soapModel.getStructureKey());
		model.setClassName(soapModel.getClassName());
		model.setClassPK(soapModel.getClassPK());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DDMStructureEntryLink> toModels(
		DDMStructureEntryLinkSoap[] soapModels) {
		List<DDMStructureEntryLink> models = new ArrayList<DDMStructureEntryLink>(soapModels.length);

		for (DDMStructureEntryLinkSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.portal.util.PropsUtil.get(
				"lock.expiration.time.com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink"));

	public DDMStructureEntryLinkModelImpl() {
	}

	public long getPrimaryKey() {
		return _structureEntryLinkId;
	}

	public void setPrimaryKey(long pk) {
		setStructureEntryLinkId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_structureEntryLinkId);
	}

	public long getStructureEntryLinkId() {
		return _structureEntryLinkId;
	}

	public void setStructureEntryLinkId(long structureEntryLinkId) {
		_structureEntryLinkId = structureEntryLinkId;
	}

	public String getStructureKey() {
		if (_structureKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _structureKey;
		}
	}

	public void setStructureKey(String structureKey) {
		if (_originalStructureKey == null) {
			_originalStructureKey = _structureKey;
		}

		_structureKey = structureKey;
	}

	public String getOriginalStructureKey() {
		return GetterUtil.getString(_originalStructureKey);
	}

	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	public void setClassName(String className) {
		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	public long getClassPK() {
		return _classPK;
	}

	public void setClassPK(long classPK) {
		if (!_setOriginalClassPK) {
			_setOriginalClassPK = true;

			_originalClassPK = _classPK;
		}

		_classPK = classPK;
	}

	public long getOriginalClassPK() {
		return _originalClassPK;
	}

	public DDMStructureEntryLink toEscapedModel() {
		if (isEscapedModel()) {
			return (DDMStructureEntryLink)this;
		}
		else {
			return (DDMStructureEntryLink)Proxy.newProxyInstance(DDMStructureEntryLink.class.getClassLoader(),
				new Class[] { DDMStructureEntryLink.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(0,
					DDMStructureEntryLink.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		DDMStructureEntryLinkImpl ddmStructureEntryLinkImpl = new DDMStructureEntryLinkImpl();

		ddmStructureEntryLinkImpl.setStructureEntryLinkId(getStructureEntryLinkId());

		ddmStructureEntryLinkImpl.setStructureKey(getStructureKey());

		DDMStructureEntryLinkModelImpl ddmStructureEntryLinkModelImpl = ddmStructureEntryLinkImpl;

		ddmStructureEntryLinkModelImpl._originalStructureKey = ddmStructureEntryLinkModelImpl._structureKey;

		ddmStructureEntryLinkImpl.setClassName(getClassName());

		ddmStructureEntryLinkModelImpl._originalClassName = ddmStructureEntryLinkModelImpl._className;

		ddmStructureEntryLinkImpl.setClassPK(getClassPK());

		ddmStructureEntryLinkModelImpl._originalClassPK = ddmStructureEntryLinkModelImpl._classPK;

		ddmStructureEntryLinkModelImpl._setOriginalClassPK = false;

		return ddmStructureEntryLinkImpl;
	}

	public int compareTo(DDMStructureEntryLink ddmStructureEntryLink) {
		long pk = ddmStructureEntryLink.getPrimaryKey();

		if (getPrimaryKey() < pk) {
			return -1;
		}
		else if (getPrimaryKey() > pk) {
			return 1;
		}
		else {
			return 0;
		}
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		DDMStructureEntryLink ddmStructureEntryLink = null;

		try {
			ddmStructureEntryLink = (DDMStructureEntryLink)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = ddmStructureEntryLink.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{structureEntryLinkId=");
		sb.append(getStructureEntryLinkId());
		sb.append(", structureKey=");
		sb.append(getStructureKey());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append(", classPK=");
		sb.append(getClassPK());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.portlet.dynamicdatamapping.model.DDMStructureEntryLink");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>structureEntryLinkId</column-name><column-value><![CDATA[");
		sb.append(getStructureEntryLinkId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>structureKey</column-name><column-value><![CDATA[");
		sb.append(getStructureKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classPK</column-name><column-value><![CDATA[");
		sb.append(getClassPK());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _structureEntryLinkId;
	private String _structureKey;
	private String _originalStructureKey;
	private String _className;
	private String _originalClassName;
	private long _classPK;
	private long _originalClassPK;
	private boolean _setOriginalClassPK;
	private transient ExpandoBridge _expandoBridge;
}