<definition>
	<command name="assertTextEquals">
		<case locator-key1="INFO_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="No sites were found." />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>

	<command name="click">
		<case locator-key1="ADD">
			<execute function="Click#textClickAt" value1="Add" />
		</case>
		<case locator-key1="ADD_BLANK_SITE">
			<execute function="Click#textClickAtAndWait" value1="Blank Site" />
		</case>
		<case locator-key1="BASIC_SEARCH_BUTTON">
			<execute function="Click#valueClickAtAndWait" value1="Search" />
		</case>
		<case locator-key1="SITE_MENULIST_DELETE">
			<execute function="Click#textClickAtAndWait" value1="Delete" />
		</case>
	</command>
</definition>