<definition>
	<command name="assertClick">
		<case locator-key1="MENU_STAGING">
			<execute function="AssertClick#assertTextClickAt" />
		</case>

		<case locator-key1="MENU_SAVE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" />
		</case>
	</command>

	<command name="assertElementNotPresent">
		<case locator-key1="STAGING_ENABLED_ON_PUBLIC_PAGES_CHECKBOX">
			<execute function="AssertElementNotPresent#assertNotVisible" />
		</case>
	</command>
</definition>