CREATE TABLE JBPM_ACTION (
    ID_                    NUMERIC(19,0) identity NOT NULL,
    class                  CHAR(1) NOT NULL               ,
    NAME_                  VARCHAR(255) NULL              ,
    ISPROPAGATIONALLOWED_  TINYINT NULL                   ,
    ACTIONEXPRESSION_      VARCHAR(255) NULL              ,
    ISASYNC_               TINYINT NULL                   ,
    REFERENCEDACTION_      NUMERIC(19,0) NULL             ,
    ACTIONDELEGATION_      NUMERIC(19,0) NULL             ,
    EVENT_                 NUMERIC(19,0) NULL             ,
    PROCESSDEFINITION_     NUMERIC(19,0) NULL             ,
    TIMERNAME_             VARCHAR(255) NULL              ,
    DUEDATE_               VARCHAR(255) NULL              ,
    REPEAT_                VARCHAR(255) NULL              ,
    TRANSITIONNAME_        VARCHAR(255) NULL              ,
    TIMERACTION_           NUMERIC(19,0) NULL             ,
    EXPRESSION_            VARCHAR(4000) NULL             ,
    EVENTINDEX_            INT NULL                       ,
    EXCEPTIONHANDLER_      NUMERIC(19,0) NULL             ,
    EXCEPTIONHANDLERINDEX_ INT NULL                       ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_BYTEARRAY (
    ID_             NUMERIC(19,0) identity NOT NULL,
    NAME_           VARCHAR(255) NULL              ,
    FILEDEFINITION_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_BYTEBLOCK (
    PROCESSFILE_ NUMERIC(19,0) NOT NULL,
    BYTES_ VARBINARY(1024) NULL        ,
    INDEX_ INT NOT NULL                ,
    PRIMARY KEY (PROCESSFILE_, INDEX_)
  );

CREATE TABLE JBPM_COMMENT (
    ID_                NUMERIC(19,0) identity NOT NULL,
    VERSION_           INT NOT NULL                   ,
    ACTORID_           VARCHAR(255) NULL              ,
    TIME_              DATETIME NULL                  ,
    MESSAGE_           VARCHAR(4000) NULL             ,
    TOKEN_             NUMERIC(19,0) NULL             ,
    TASKINSTANCE_      NUMERIC(19,0) NULL             ,
    TOKENINDEX_        INT NULL                       ,
    TASKINSTANCEINDEX_ INT NULL                       ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_DECISIONCONDITIONS (
    DECISION_       NUMERIC(19,0) NOT NULL,
    TRANSITIONNAME_ VARCHAR(255) NULL     ,
    EXPRESSION_     VARCHAR(255) NULL     ,
    INDEX_          INT NOT NULL          ,
    PRIMARY KEY (DECISION_, INDEX_)
  );

CREATE TABLE JBPM_DELEGATION (
    ID_                NUMERIC(19,0) identity NOT NULL,
    CLASSNAME_         VARCHAR(4000) NULL             ,
    CONFIGURATION_     VARCHAR(4000) NULL             ,
    CONFIGTYPE_        VARCHAR(255) NULL              ,
    PROCESSDEFINITION_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_EVENT (
    ID_                NUMERIC(19,0) identity NOT NULL,
    EVENTTYPE_         VARCHAR(255) NULL              ,
    TYPE_              CHAR(1) NULL                   ,
    GRAPHELEMENT_      NUMERIC(19,0) NULL             ,
    PROCESSDEFINITION_ NUMERIC(19,0) NULL             ,
    NODE_              NUMERIC(19,0) NULL             ,
    TRANSITION_        NUMERIC(19,0) NULL             ,
    TASK_              NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_EXCEPTIONHANDLER (
    ID_                 NUMERIC(19,0) identity NOT NULL,
    EXCEPTIONCLASSNAME_ VARCHAR(4000) NULL             ,
    TYPE_               CHAR(1) NULL                   ,
    GRAPHELEMENT_       NUMERIC(19,0) NULL             ,
    PROCESSDEFINITION_  NUMERIC(19,0) NULL             ,
    GRAPHELEMENTINDEX_  INT NULL                       ,
    NODE_               NUMERIC(19,0) NULL             ,
    TRANSITION_         NUMERIC(19,0) NULL             ,
    TASK_               NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_ID_GROUP (
    ID_     NUMERIC(19,0) identity NOT NULL,
    CLASS_  CHAR(1) NOT NULL               ,
    NAME_   VARCHAR(255) NULL              ,
    TYPE_   VARCHAR(255) NULL              ,
    PARENT_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_ID_MEMBERSHIP (
    ID_    NUMERIC(19,0) identity NOT NULL,
    CLASS_ CHAR(1) NOT NULL               ,
    NAME_  VARCHAR(255) NULL              ,
    ROLE_  VARCHAR(255) NULL              ,
    USER_  NUMERIC(19,0) NULL             ,
    GROUP_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_ID_PERMISSIONS (
    ENTITY_ NUMERIC(19,0) NOT NULL,
    CLASS_  VARCHAR(255) NULL     ,
    NAME_   VARCHAR(255) NULL     ,
    ACTION_ VARCHAR(255) NULL
  );

CREATE TABLE JBPM_ID_USER (
    ID_       NUMERIC(19,0) identity NOT NULL,
    CLASS_    CHAR(1) NOT NULL               ,
    NAME_     VARCHAR(255) NULL              ,
    EMAIL_    VARCHAR(255) NULL              ,
    PASSWORD_ VARCHAR(255) NULL              ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_LOG (
    ID_               NUMERIC(19,0) identity NOT NULL,
    CLASS_            CHAR(1) NOT NULL               ,
    INDEX_            INT NULL                       ,
    DATE_             DATETIME NULL                  ,
    TOKEN_            NUMERIC(19,0) NULL             ,
    PARENT_           NUMERIC(19,0) NULL             ,
    MESSAGE_          VARCHAR(4000) NULL             ,
    EXCEPTION_        VARCHAR(4000) NULL             ,
    ACTION_           NUMERIC(19,0) NULL             ,
    NODE_             NUMERIC(19,0) NULL             ,
    ENTER_            DATETIME NULL                  ,
    LEAVE_            DATETIME NULL                  ,
    DURATION_         NUMERIC(19,0) NULL             ,
    NEWLONGVALUE_     NUMERIC(19,0) NULL             ,
    TRANSITION_       NUMERIC(19,0) NULL             ,
    CHILD_            NUMERIC(19,0) NULL             ,
    SOURCENODE_       NUMERIC(19,0) NULL             ,
    DESTINATIONNODE_  NUMERIC(19,0) NULL             ,
    VARIABLEINSTANCE_ NUMERIC(19,0) NULL             ,
    OLDBYTEARRAY_     NUMERIC(19,0) NULL             ,
    NEWBYTEARRAY_     NUMERIC(19,0) NULL             ,
    OLDDATEVALUE_     DATETIME NULL                  ,
    NEWDATEVALUE_     DATETIME NULL                  ,
    OLDDOUBLEVALUE_ DOUBLE PRECISION NULL            ,
    NEWDOUBLEVALUE_ DOUBLE PRECISION NULL            ,
    OLDLONGIDCLASS_   VARCHAR(255) NULL                ,
    OLDLONGIDVALUE_   NUMERIC(19,0) NULL               ,
    NEWLONGIDCLASS_   VARCHAR(255) NULL                ,
    NEWLONGIDVALUE_   NUMERIC(19,0) NULL               ,
    OLDSTRINGIDCLASS_ VARCHAR(255) NULL                ,
    OLDSTRINGIDVALUE_ VARCHAR(255) NULL                ,
    NEWSTRINGIDCLASS_ VARCHAR(255) NULL                ,
    NEWSTRINGIDVALUE_ VARCHAR(255) NULL                ,
    OLDLONGVALUE_     NUMERIC(19,0) NULL               ,
    OLDSTRINGVALUE_   VARCHAR(4000) NULL               ,
    NEWSTRINGVALUE_   VARCHAR(4000) NULL               ,
    TASKINSTANCE_     NUMERIC(19,0) NULL               ,
    TASKACTORID_      VARCHAR(255) NULL                ,
    TASKOLDACTORID_   VARCHAR(255) NULL                ,
    SWIMLANEINSTANCE_ NUMERIC(19,0) NULL               ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_MESSAGE (
    ID_             NUMERIC(19,0) identity NOT NULL,
    CLASS_          CHAR(1) NOT NULL               ,
    DESTINATION_    VARCHAR(255) NULL              ,
    EXCEPTION_      VARCHAR(4000) NULL             ,
    ISSUSPENDED_    TINYINT NULL                   ,
    TOKEN_          NUMERIC(19,0) NULL             ,
    TEXT_           VARCHAR(255) NULL              ,
    ACTION_         NUMERIC(19,0) NULL             ,
    NODE_           NUMERIC(19,0) NULL             ,
    TRANSITIONNAME_ VARCHAR(255) NULL              ,
    TASKINSTANCE_   NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_MODULEDEFINITION (
    ID_                NUMERIC(19,0) identity NOT NULL,
    CLASS_             CHAR(1) NOT NULL               ,
    NAME_              VARCHAR(4000) NULL             ,
    PROCESSDEFINITION_ NUMERIC(19,0) NULL             ,
    STARTTASK_         NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_MODULEINSTANCE (
    ID_                 NUMERIC(19,0) identity NOT NULL,
    CLASS_              CHAR(1) NOT NULL               ,
    PROCESSINSTANCE_    NUMERIC(19,0) NULL             ,
    TASKMGMTDEFINITION_ NUMERIC(19,0) NULL             ,
    NAME_               VARCHAR(255) NULL              ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_NODE (
    ID_                   NUMERIC(19,0) identity NOT NULL,
    CLASS_                CHAR(1) NOT NULL               ,
    NAME_                 VARCHAR(255) NULL              ,
    PROCESSDEFINITION_    NUMERIC(19,0) NULL             ,
    ISASYNC_              TINYINT NULL                   ,
    ACTION_               NUMERIC(19,0) NULL             ,
    SUPERSTATE_           NUMERIC(19,0) NULL             ,
    SUBPROCESSDEFINITION_ NUMERIC(19,0) NULL             ,
    DECISIONEXPRESSION_   VARCHAR(255) NULL              ,
    DECISIONDELEGATION    NUMERIC(19,0) NULL             ,
    SIGNAL_               INT NULL                       ,
    CREATETASKS_          TINYINT NULL                   ,
    ENDTASKS_             TINYINT NULL                   ,
    NODECOLLECTIONINDEX_  INT NULL                       ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_POOLEDACTOR (
    ID_               NUMERIC(19,0) identity NOT NULL,
    ACTORID_          VARCHAR(255) NULL              ,
    SWIMLANEINSTANCE_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_PROCESSDEFINITION (
    ID_                    NUMERIC(19,0) identity NOT NULL,
    NAME_                  VARCHAR(255) NULL              ,
    VERSION_               INT NULL                       ,
    ISTERMINATIONIMPLICIT_ TINYINT NULL                   ,
    STARTSTATE_            NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_PROCESSINSTANCE (
    ID_                NUMERIC(19,0) identity NOT NULL,
    VERSION_           INT NOT NULL                   ,
    START_             DATETIME NULL                  ,
    END_               DATETIME NULL                  ,
    ISSUSPENDED_       TINYINT NULL                   ,
    PROCESSDEFINITION_ NUMERIC(19,0) NULL             ,
    ROOTTOKEN_         NUMERIC(19,0) NULL             ,
    SUPERPROCESSTOKEN_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_RUNTIMEACTION (
    ID_                   NUMERIC(19,0) identity NOT NULL,
    VERSION_              INT NOT NULL                   ,
    EVENTTYPE_            VARCHAR(255) NULL              ,
    TYPE_                 CHAR(1) NULL                   ,
    GRAPHELEMENT_         NUMERIC(19,0) NULL             ,
    PROCESSINSTANCE_      NUMERIC(19,0) NULL             ,
    ACTION_               NUMERIC(19,0) NULL             ,
    PROCESSINSTANCEINDEX_ INT NULL                       ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_SWIMLANE (
    ID_                     NUMERIC(19,0) identity NOT NULL,
    NAME_                   VARCHAR(255) NULL              ,
    ACTORIDEXPRESSION_      VARCHAR(255) NULL              ,
    POOLEDACTORSEXPRESSION_ VARCHAR(255) NULL              ,
    ASSIGNMENTDELEGATION_   NUMERIC(19,0) NULL             ,
    TASKMGMTDEFINITION_     NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_SWIMLANEINSTANCE (
    ID_               NUMERIC(19,0) identity NOT NULL,
    NAME_             VARCHAR(255) NULL              ,
    ACTORID_          VARCHAR(255) NULL              ,
    SWIMLANE_         NUMERIC(19,0) NULL             ,
    TASKMGMTINSTANCE_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TASK (
    ID_                     NUMERIC(19,0) identity NOT NULL,
    NAME_                   VARCHAR(255) NULL              ,
    PROCESSDEFINITION_      NUMERIC(19,0) NULL             ,
    DESCRIPTION_            VARCHAR(4000) NULL             ,
    ISBLOCKING_             TINYINT NULL                   ,
    ISSIGNALLING_           TINYINT NULL                   ,
    DUEDATE_                VARCHAR(255) NULL              ,
    ACTORIDEXPRESSION_      VARCHAR(255) NULL              ,
    POOLEDACTORSEXPRESSION_ VARCHAR(255) NULL              ,
    TASKMGMTDEFINITION_     NUMERIC(19,0) NULL             ,
    TASKNODE_               NUMERIC(19,0) NULL             ,
    STARTSTATE_             NUMERIC(19,0) NULL             ,
    ASSIGNMENTDELEGATION_   NUMERIC(19,0) NULL             ,
    SWIMLANE_               NUMERIC(19,0) NULL             ,
    TASKCONTROLLER_         NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TASKACTORPOOL (
    TASKINSTANCE_ NUMERIC(19,0) NOT NULL,
    POOLEDACTOR_  NUMERIC(19,0) NOT NULL,
    PRIMARY KEY (TASKINSTANCE_, POOLEDACTOR_)
  );

CREATE TABLE JBPM_TASKCONTROLLER (
    ID_                       NUMERIC(19,0) identity NOT NULL,
    TASKCONTROLLERDELEGATION_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TASKINSTANCE (
    ID_               NUMERIC(19,0) identity NOT NULL,
    CLASS_            CHAR(1) NOT NULL               ,
    NAME_             VARCHAR(255) NULL              ,
    DESCRIPTION_      VARCHAR(4000) NULL             ,
    ACTORID_          VARCHAR(255) NULL              ,
    CREATE_           DATETIME NULL                  ,
    START_            DATETIME NULL                  ,
    END_              DATETIME NULL                  ,
    DUEDATE_          DATETIME NULL                  ,
    PRIORITY_         INT NULL                       ,
    ISCANCELLED_      TINYINT NULL                   ,
    ISSUSPENDED_      TINYINT NULL                   ,
    ISOPEN_           TINYINT NULL                   ,
    ISSIGNALLING_     TINYINT NULL                   ,
    ISBLOCKING_       TINYINT NULL                   ,
    TASK_             NUMERIC(19,0) NULL             ,
    TOKEN_            NUMERIC(19,0) NULL             ,
    SWIMLANINSTANCE_  NUMERIC(19,0) NULL             ,
    TASKMGMTINSTANCE_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TIMER (
    ID_               NUMERIC(19,0) identity NOT NULL,
    NAME_             VARCHAR(255) NULL              ,
    DUEDATE_          DATETIME NULL                  ,
    REPEAT_           VARCHAR(255) NULL              ,
    TRANSITIONNAME_   VARCHAR(255) NULL              ,
    EXCEPTION_        VARCHAR(4000) NULL             ,
    ISSUSPENDED_      TINYINT NULL                   ,
    ACTION_           NUMERIC(19,0) NULL             ,
    TOKEN_            NUMERIC(19,0) NULL             ,
    PROCESSINSTANCE_  NUMERIC(19,0) NULL             ,
    TASKINSTANCE_     NUMERIC(19,0) NULL             ,
    GRAPHELEMENTTYPE_ VARCHAR(255) NULL              ,
    GRAPHELEMENT_     NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TOKEN (
    ID_                       NUMERIC(19,0) identity NOT NULL,
    VERSION_                  INT NOT NULL                   ,
    NAME_                     VARCHAR(255) NULL              ,
    START_                    DATETIME NULL                  ,
    END_                      DATETIME NULL                  ,
    NODEENTER_                DATETIME NULL                  ,
    NEXTLOGINDEX_             INT NULL                       ,
    ISABLETOREACTIVATEPARENT_ TINYINT NULL                   ,
    ISTERMINATIONIMPLICIT_    TINYINT NULL                   ,
    ISSUSPENDED_              TINYINT NULL                   ,
    NODE_                     NUMERIC(19,0) NULL             ,
    PROCESSINSTANCE_          NUMERIC(19,0) NULL             ,
    PARENT_                   NUMERIC(19,0) NULL             ,
    SUBPROCESSINSTANCE_       NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TOKENVARIABLEMAP (
    ID_              NUMERIC(19,0) identity NOT NULL,
    TOKEN_           NUMERIC(19,0) NULL             ,
    CONTEXTINSTANCE_ NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_TRANSITION (
    ID_                NUMERIC(19,0) identity NOT NULL,
    NAME_              VARCHAR(255) NULL              ,
    PROCESSDEFINITION_ NUMERIC(19,0) NULL             ,
    FROM_              NUMERIC(19,0) NULL             ,
    TO_                NUMERIC(19,0) NULL             ,
    FROMINDEX_         INT NULL                       ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_VARIABLEACCESS (
    ID_             NUMERIC(19,0) identity NOT NULL,
    VARIABLENAME_   VARCHAR(255) NULL              ,
    ACCESS_         VARCHAR(255) NULL              ,
    MAPPEDNAME_     VARCHAR(255) NULL              ,
    PROCESSSTATE_   NUMERIC(19,0) NULL             ,
    TASKCONTROLLER_ NUMERIC(19,0) NULL             ,
    INDEX_          INT NULL                       ,
    SCRIPT_         NUMERIC(19,0) NULL             ,
    PRIMARY KEY (ID_)
  );

CREATE TABLE JBPM_VARIABLEINSTANCE (
    ID_               NUMERIC(19,0) identity NOT NULL,
    CLASS_            CHAR(1) NOT NULL               ,
    NAME_             VARCHAR(255) NULL              ,
    CONVERTER_        CHAR(1) NULL                   ,
    TOKEN_            NUMERIC(19,0) NULL             ,
    TOKENVARIABLEMAP_ NUMERIC(19,0) NULL             ,
    PROCESSINSTANCE_  NUMERIC(19,0) NULL             ,
    BYTEARRAYVALUE_   NUMERIC(19,0) NULL             ,
    DATEVALUE_        DATETIME NULL                  ,
    DOUBLEVALUE_ DOUBLE PRECISION NULL               ,
    LONGIDCLASS_   VARCHAR(255) NULL                   ,
    LONGVALUE_     NUMERIC(19,0) NULL                  ,
    STRINGIDCLASS_ VARCHAR(255) NULL                   ,
    STRINGVALUE_   VARCHAR(255) NULL                   ,
    TASKINSTANCE_  NUMERIC(19,0) NULL                  ,
    PRIMARY KEY (ID_)
  );

ALTER TABLE JBPM_ACTION ADD CONSTRAINT FK_ACTION_EVENT FOREIGN KEY(
  EVENT_
)
REFERENCES JBPM_EVENT;
ALTER TABLE JBPM_ACTION ADD CONSTRAINT FK_ACTION_EXPTHDL FOREIGN KEY(
  EXCEPTIONHANDLER_
)
REFERENCES JBPM_EXCEPTIONHANDLER;
ALTER TABLE JBPM_ACTION ADD CONSTRAINT FK_ACTION_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_ACTION ADD CONSTRAINT FK_CRTETIMERACT_TA FOREIGN KEY(
  TIMERACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_ACTION ADD CONSTRAINT FK_ACTION_ACTNDEL FOREIGN KEY(
  ACTIONDELEGATION_
)
REFERENCES JBPM_DELEGATION;
ALTER TABLE JBPM_ACTION ADD CONSTRAINT FK_ACTION_REFACT FOREIGN KEY(
  REFERENCEDACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_BYTEARRAY ADD CONSTRAINT FK_BYTEARR_FILDEF FOREIGN KEY(
  FILEDEFINITION_
)
REFERENCES JBPM_MODULEDEFINITION;
ALTER TABLE JBPM_BYTEBLOCK ADD CONSTRAINT FK_BYTEBLOCK_FILE FOREIGN KEY(
  PROCESSFILE_
)
REFERENCES JBPM_BYTEARRAY;
ALTER TABLE JBPM_COMMENT ADD CONSTRAINT FK_COMMENT_TOKEN FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_COMMENT ADD CONSTRAINT FK_COMMENT_TSK FOREIGN KEY(
  TASKINSTANCE_
)
REFERENCES JBPM_TASKINSTANCE;
ALTER TABLE JBPM_DECISIONCONDITIONS ADD CONSTRAINT FK_DECCOND_DEC FOREIGN KEY(
  DECISION_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_DELEGATION ADD CONSTRAINT FK_DELEGATION_PRCD FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_EVENT ADD CONSTRAINT FK_EVENT_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_EVENT ADD CONSTRAINT FK_EVENT_NODE FOREIGN KEY(
  NODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_EVENT ADD CONSTRAINT FK_EVENT_TRANS FOREIGN KEY(
  TRANSITION_
)
REFERENCES JBPM_TRANSITION;
ALTER TABLE JBPM_EVENT ADD CONSTRAINT FK_EVENT_TASK FOREIGN KEY(
  TASK_
)
REFERENCES JBPM_TASK;
ALTER TABLE JBPM_ID_GROUP ADD CONSTRAINT FK_ID_GRP_PARENT FOREIGN KEY(
  PARENT_
)
REFERENCES JBPM_ID_GROUP;
ALTER TABLE JBPM_ID_MEMBERSHIP ADD CONSTRAINT FK_ID_MEMSHIP_GRP FOREIGN KEY(
  GROUP_
)
REFERENCES JBPM_ID_GROUP;
ALTER TABLE JBPM_ID_MEMBERSHIP ADD CONSTRAINT FK_ID_MEMSHIP_USR FOREIGN KEY(
  USER_
)
REFERENCES JBPM_ID_USER;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_SOURCENODE FOREIGN KEY(
  SOURCENODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_TOKEN FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_OLDBYTES FOREIGN KEY(
  OLDBYTEARRAY_
)
REFERENCES JBPM_BYTEARRAY;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_NEWBYTES FOREIGN KEY(
  NEWBYTEARRAY_
)
REFERENCES JBPM_BYTEARRAY;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_CHILDTOKEN FOREIGN KEY(
  CHILD_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_DESTNODE FOREIGN KEY(
  DESTINATIONNODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_TASKINST FOREIGN KEY(
  TASKINSTANCE_
)
REFERENCES JBPM_TASKINSTANCE;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_SWIMINST FOREIGN KEY(
  SWIMLANEINSTANCE_
)
REFERENCES JBPM_SWIMLANEINSTANCE;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_PARENT FOREIGN KEY(
  PARENT_
)
REFERENCES JBPM_LOG;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_NODE FOREIGN KEY(
  NODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_ACTION FOREIGN KEY(
  ACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_VARINST FOREIGN KEY(
  VARIABLEINSTANCE_
)
REFERENCES JBPM_VARIABLEINSTANCE;
ALTER TABLE JBPM_LOG ADD CONSTRAINT FK_LOG_TRANSITION FOREIGN KEY(
  TRANSITION_
)
REFERENCES JBPM_TRANSITION;
ALTER TABLE JBPM_MESSAGE ADD CONSTRAINT FK_MSG_TOKEN FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_MESSAGE ADD CONSTRAINT FK_CMD_NODE FOREIGN KEY(
  NODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_MESSAGE ADD CONSTRAINT FK_CMD_ACTION FOREIGN KEY(
  ACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_MESSAGE ADD CONSTRAINT FK_CMD_TASKINST FOREIGN KEY(
  TASKINSTANCE_
)
REFERENCES JBPM_TASKINSTANCE;
ALTER TABLE JBPM_MODULEDEFINITION ADD CONSTRAINT FK_TSKDEF_START FOREIGN KEY(
  STARTTASK_
)
REFERENCES JBPM_TASK;
ALTER TABLE JBPM_MODULEDEFINITION ADD CONSTRAINT FK_MODDEF_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_MODULEINSTANCE ADD CONSTRAINT FK_TASKMGTINST_TMD FOREIGN KEY(
  TASKMGMTDEFINITION_
)
REFERENCES JBPM_MODULEDEFINITION;
ALTER TABLE JBPM_MODULEINSTANCE ADD CONSTRAINT FK_MODINST_PRCINST FOREIGN KEY(
  PROCESSINSTANCE_
)
REFERENCES JBPM_PROCESSINSTANCE;
ALTER TABLE JBPM_NODE ADD CONSTRAINT FK_PROCST_SBPRCDEF FOREIGN KEY(
  SUBPROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_NODE ADD CONSTRAINT FK_NODE_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_NODE ADD CONSTRAINT FK_NODE_ACTION FOREIGN KEY(
  ACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_NODE ADD CONSTRAINT FK_DECISION_DELEG FOREIGN KEY(
  DECISIONDELEGATION
)
REFERENCES JBPM_DELEGATION;
ALTER TABLE JBPM_NODE ADD CONSTRAINT FK_NODE_SUPERSTATE FOREIGN KEY(
  SUPERSTATE_
)
REFERENCES JBPM_NODE;
CREATE INDEX IDX_PLDACTR_ACTID ON JBPM_POOLEDACTOR
  (
    ACTORID_
  );

ALTER TABLE JBPM_POOLEDACTOR ADD CONSTRAINT FK_POOLEDACTOR_SLI FOREIGN KEY(
  SWIMLANEINSTANCE_
)
REFERENCES JBPM_SWIMLANEINSTANCE;
ALTER TABLE JBPM_PROCESSDEFINITION ADD CONSTRAINT FK_PROCDEF_STRTSTA FOREIGN KEY(
  STARTSTATE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_PROCESSINSTANCE ADD CONSTRAINT FK_PROCIN_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_PROCESSINSTANCE ADD CONSTRAINT FK_PROCIN_ROOTTKN FOREIGN KEY(
  ROOTTOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_PROCESSINSTANCE ADD CONSTRAINT FK_PROCIN_SPROCTKN FOREIGN KEY(
  SUPERPROCESSTOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_RUNTIMEACTION ADD CONSTRAINT FK_RTACTN_PROCINST FOREIGN KEY(
  PROCESSINSTANCE_
)
REFERENCES JBPM_PROCESSINSTANCE;
ALTER TABLE JBPM_RUNTIMEACTION ADD CONSTRAINT FK_RTACTN_ACTION FOREIGN KEY(
  ACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_SWIMLANE ADD CONSTRAINT FK_SWL_ASSDEL FOREIGN KEY(
  ASSIGNMENTDELEGATION_
)
REFERENCES JBPM_DELEGATION;
ALTER TABLE JBPM_SWIMLANE ADD CONSTRAINT FK_SWL_TSKMGMTDEF FOREIGN KEY(
  TASKMGMTDEFINITION_
)
REFERENCES JBPM_MODULEDEFINITION;
ALTER TABLE JBPM_SWIMLANEINSTANCE ADD CONSTRAINT FK_SWIMLANEINST_TM FOREIGN KEY(
  TASKMGMTINSTANCE_
)
REFERENCES JBPM_MODULEINSTANCE;
ALTER TABLE JBPM_SWIMLANEINSTANCE ADD CONSTRAINT FK_SWIMLANEINST_SL FOREIGN KEY(
  SWIMLANE_
)
REFERENCES JBPM_SWIMLANE;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TSK_TSKCTRL FOREIGN KEY(
  TASKCONTROLLER_
)
REFERENCES JBPM_TASKCONTROLLER;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TASK_ASSDEL FOREIGN KEY(
  ASSIGNMENTDELEGATION_
)
REFERENCES JBPM_DELEGATION;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TASK_TASKNODE FOREIGN KEY(
  TASKNODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TASK_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TASK_STARTST FOREIGN KEY(
  STARTSTATE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TASK_TASKMGTDEF FOREIGN KEY(
  TASKMGMTDEFINITION_
)
REFERENCES JBPM_MODULEDEFINITION;
ALTER TABLE JBPM_TASK ADD CONSTRAINT FK_TASK_SWIMLANE FOREIGN KEY(
  SWIMLANE_
)
REFERENCES JBPM_SWIMLANE;
ALTER TABLE JBPM_TASKACTORPOOL ADD CONSTRAINT FK_TSKACTPOL_PLACT FOREIGN KEY(
  POOLEDACTOR_
)
REFERENCES JBPM_POOLEDACTOR;
ALTER TABLE JBPM_TASKACTORPOOL ADD CONSTRAINT FK_TASKACTPL_TSKI FOREIGN KEY(
  TASKINSTANCE_
)
REFERENCES JBPM_TASKINSTANCE;
ALTER TABLE JBPM_TASKCONTROLLER ADD CONSTRAINT FK_TSKCTRL_DELEG FOREIGN KEY(
  TASKCONTROLLERDELEGATION_
)
REFERENCES JBPM_DELEGATION;
CREATE INDEX IDX_TASK_ACTORID ON JBPM_TASKINSTANCE(
    ACTORID_
  );

ALTER TABLE JBPM_TASKINSTANCE ADD CONSTRAINT FK_TASKINST_TMINST FOREIGN KEY(
  TASKMGMTINSTANCE_
)
REFERENCES JBPM_MODULEINSTANCE;
ALTER TABLE JBPM_TASKINSTANCE ADD CONSTRAINT FK_TASKINST_TOKEN FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_TASKINSTANCE ADD CONSTRAINT FK_TASKINST_SLINST FOREIGN KEY(
  SWIMLANINSTANCE_
)
REFERENCES JBPM_SWIMLANEINSTANCE;
ALTER TABLE JBPM_TASKINSTANCE ADD CONSTRAINT FK_TASKINST_TASK FOREIGN KEY(
  TASK_
)
REFERENCES JBPM_TASK;
ALTER TABLE JBPM_TIMER ADD CONSTRAINT FK_TIMER_TOKEN FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_TIMER ADD CONSTRAINT FK_TIMER_PRINST FOREIGN KEY(
  PROCESSINSTANCE_
)
REFERENCES JBPM_PROCESSINSTANCE;
ALTER TABLE JBPM_TIMER ADD CONSTRAINT FK_TIMER_ACTION FOREIGN KEY(
  ACTION_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_TIMER ADD CONSTRAINT FK_TIMER_TSKINST FOREIGN KEY(
  TASKINSTANCE_
)
REFERENCES JBPM_TASKINSTANCE;
ALTER TABLE JBPM_TOKEN ADD CONSTRAINT FK_TOKEN_PARENT FOREIGN KEY(
  PARENT_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_TOKEN ADD CONSTRAINT FK_TOKEN_NODE FOREIGN KEY(
  NODE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_TOKEN ADD CONSTRAINT FK_TOKEN_PROCINST FOREIGN KEY(
  PROCESSINSTANCE_
)
REFERENCES JBPM_PROCESSINSTANCE;
ALTER TABLE JBPM_TOKEN ADD CONSTRAINT FK_TOKEN_SUBPI FOREIGN KEY(
  SUBPROCESSINSTANCE_
)
REFERENCES JBPM_PROCESSINSTANCE;
ALTER TABLE JBPM_TOKENVARIABLEMAP ADD CONSTRAINT FK_TKVARMAP_CTXT FOREIGN KEY(
  CONTEXTINSTANCE_
)
REFERENCES JBPM_MODULEINSTANCE;
ALTER TABLE JBPM_TOKENVARIABLEMAP ADD CONSTRAINT FK_TKVARMAP_TOKEN FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_TRANSITION ADD CONSTRAINT FK_TRANSITION_TO FOREIGN KEY(
  TO_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_TRANSITION ADD CONSTRAINT FK_TRANS_PROCDEF FOREIGN KEY(
  PROCESSDEFINITION_
)
REFERENCES JBPM_PROCESSDEFINITION;
ALTER TABLE JBPM_TRANSITION ADD CONSTRAINT FK_TRANSITION_FROM FOREIGN KEY(
  FROM_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_VARIABLEACCESS ADD CONSTRAINT FK_VARACC_TSKCTRL FOREIGN KEY(
  TASKCONTROLLER_
)
REFERENCES JBPM_TASKCONTROLLER;
ALTER TABLE JBPM_VARIABLEACCESS ADD CONSTRAINT FK_VARACC_SCRIPT FOREIGN KEY(
  SCRIPT_
)
REFERENCES JBPM_ACTION;
ALTER TABLE JBPM_VARIABLEACCESS ADD CONSTRAINT FK_VARACC_PROCST FOREIGN KEY(
  PROCESSSTATE_
)
REFERENCES JBPM_NODE;
ALTER TABLE JBPM_VARIABLEINSTANCE ADD CONSTRAINT FK_VARINST_TK FOREIGN KEY(
  TOKEN_
)
REFERENCES JBPM_TOKEN;
ALTER TABLE JBPM_VARIABLEINSTANCE ADD CONSTRAINT FK_VARINST_TKVARMP FOREIGN KEY(
  TOKENVARIABLEMAP_
)
REFERENCES JBPM_TOKENVARIABLEMAP;
ALTER TABLE JBPM_VARIABLEINSTANCE ADD CONSTRAINT FK_VARINST_PRCINST FOREIGN KEY(
  PROCESSINSTANCE_
)
REFERENCES JBPM_PROCESSINSTANCE;
ALTER TABLE JBPM_VARIABLEINSTANCE ADD CONSTRAINT FK_VAR_TSKINST FOREIGN KEY(
  TASKINSTANCE_
)
REFERENCES JBPM_TASKINSTANCE;
ALTER TABLE JBPM_VARIABLEINSTANCE ADD CONSTRAINT FK_BYTEINST_ARRAY FOREIGN KEY(
  BYTEARRAYVALUE_
)
REFERENCES JBPM_BYTEARRAY;