<definition>
	<command name="assertClick">
		<case locator-key1="WIKI_PAGE_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
		<case locator-key1="WIKI_PAGE_MENULIST_DELETE">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>