<definition>
	<command name="click">
		<case locator-key1="ADD_WIKI">
			<execute function="Click#valueClickAtAndWait" value1="Add Wiki" />
		</case>
		<case comparator="startsWith" locator-key1="WIKI_NODE_TABLE_ACTIONS_">
			<execute function="Click#pauseTextClickAt" value1="Actions" />
		</case>
		<case locator-key1="WIKI_NODE_ACTIONS_RECYCLE_BIN">
			<execute function="Click#textClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
	</command>
</definition>