<definition>
	<command name="assertClick">
		<case locator-key1="ADD_WIKI_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" value1="Add Wiki" />
		</case>
		<case locator-key1="WIKI_NODE_MENULIST_EDIT">
			<execute function="AssertClick#assertTextClickAtAndWait" value1="Edit" />
		</case>
		<case locator-key1="WIKI_NODE_MENULIST_RECYCLE_BIN">
			<execute function="AssertClick#assertTextClickAtAndWait" value1="Move to the Recycle Bin" />
		</case>
		<case locator-key1="WIKI_NODE_TABLE_ACTIONS">
			<execute function="AssertClick#pauseAssertTextClickAt" value1="Actions" />
		</case>
		<case locator-key1="WIKI_NODE_TABLE_WIKI">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>

	<command name="assertTextEquals">
		<case locator-key1="SUCCESS_MESSAGE_RECYCLE_BIN">
			<execute function="AssertTextEquals#assertPartialText" value1="The selected item was moved to the Recycle Bin. Undo" />
		</case>
		<case locator-key1="SUCCESS_MESSAGE">
			<execute function="AssertTextEquals#assertText" value1="Your request completed successfully." />
		</case>
	</command>
</definition>