<definition>
	<command name="assertClick">
		<case locator-key1="NAVIGATION_AVAILABLE_SITES">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>

		<case locator-key1="SEARCH_BUTTON">
			<execute function="AssertClick#assertTextClickAtAndWait" />
		</case>
	</command>
</definition>