<definition>
	<command name="assertTextEquals">
		<case locator-key1="SITE_CLONED_FROM_TEMPLATE_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>

		<case locator-key1="SITE_NOT_CLONED_FROM_TEMPLATE_MESSAGE">
			<execute function="AssertTextEquals#assertPartialText" />
		</case>
	</command>
</definition>